---
title: "GDP3만불시대"
author: "coop711"
date: '`r Sys.Date()`'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data

```{r, data}
library(xlsx)
GDP <- read.xlsx("../data/GDP_per_Capita.xlsx", 1, colIndex = 2:3, colClasses = c("integer", "numeric"), header = TRUE, stringsAsFactors = FALSE)
str(GDP)
year <- GDP$시점
gdp <- GDP$데이터
event.year <- c(1953, 1977, 1989, 1994, 1998, 2006, 2009, 2015)
gov.year.1 <- c(1953, 1979, 1987, 1992, 1997, 2002, 2007, 2012, 2015)
gov.year.2 <- c(1953, 1980, 1988, 1993, 1998, 2003, 2008, 2013, 2015)
gov.period.1 <- diff(gov.year.1)
gov.period.2 <- diff(gov.year.2)
gdp[year %in% gov.year.1]
gdp[year %in% gov.year.2]
gdp.head.1 <- head(gdp[year %in% gov.year.1], -1)
gdp.tail.1 <- tail(gdp[year %in% gov.year.1], -1)
(rate.1 <- round(((gdp.tail.1/gdp.head.1)^(1/(gov.period.1)) - 1)*100, digits = 1))
gdp.head.2 <- head(gdp[year %in% gov.year.2], -1)
gdp.tail.2 <- tail(gdp[year %in% gov.year.2], -1)
(rate.2 <- round(((gdp.tail.2/gdp.head.2)^(1/(gov.period.2)) - 1)*100, digits = 1))
```

## Plot

```{r, plot, fig.width = 12, fig.height = 9}
par(family = "HCR Dotum LVT")
plot(GDP, type = "b", pch = 17, xaxt = "n", yaxt = "n", ylab = "", xlim = c(1950, 2020), ylim = c(0, 30000))
axis(side = 1, at = event.year, labels = event.year)
axis(side = 2, at = seq(0, 30000, by = 5000), labels = paste(seq(0, 30, by = 5), "천불", sep = ""), las = 2)
abline(h = seq(0, 30000, by = 5000), lty = 3)
abline(v = event.year, lty = 3)
text(x = event.year, y = GDP[GDP$시점 %in% event.year, 2], labels = c("66불", "1천불", "5천불", "1만불", "IMF 위기", "2만불", "서브프라임 위기", "ㅁㅁㅁ 위기"), pos = c(3, 3, 2, 2, 4, 2, 4, 4), col = c(rep("blue", 4), "red", "blue", "red", "red"))
title(main = "1인당 국내총생산(명목, 달러표시)", cex.main = 2.0)
dev.copy(png, file = "../pics/GDP_per_capita_kr.png", width = 640, height = 480)
```
