---
title: "Invisible Gorilla 201601"
author: "coop711"
date: "`r Sys.Date()`"
output: html_document
---

### Data

#### Read In

```{r, library and read, echo = FALSE, message = FALSE, results = 'hide'}
library(xlsx)
library(pander)
library(ggplot2)
options(digits=3)
# gorilla <- read.xlsx("../../class201601/data/gorilla0601.xlsx", 1, startRow = 2, endRow = 66, header = FALSE, colIndex = c(3:7, 9:31), colClasses = c(rep("character", 17), "numeric", "character", "numeric", rep("character", 6), "numeric", "character"))
load("./gorilla_0601.rda")
str(gorilla)
```

#### Management

```{r, data restructuring, echo = FALSE, results='hide'}
names(gorilla) <- c("dept", "id", "name", "year", "e.mail", "cell.no", "Q1", "Q2.1", "Q2.2", "Q2.3", "Q3", "Q4.1", "Q4.2", "Q4.3", "Q4.4", "Q4.5", "Q4.6", "Q5.1", "Q5.2", "Q6.1", "Q6.2", "Q6.3", "Q6.4", "Q7", "Q8", "Q9", "Q10", "group")
gorilla$dept <- factor(gorilla$dept)
gorilla$year <- factor(gorilla$year)
gorilla$group <- factor(gorilla$group, levels = c("Red", "Black"))
str(gorilla)
wrong_diff <- factor(gorilla$Q1, levels = c("가", "나"), labels = c("틀리다", "다르다"))
monkey_panda_banana <- factor(gorilla$Q2.1, levels = c("가", "나", "다"), labels = c("원숭이와 바나나", "원숭이와 팬더", "팬더와 바나나"))
still_happy <- factor(gorilla$Q2.2, levels = c("가", "나"), labels = c("행복해 보인다", "행복해 보이지 않는다"))
which_one_in_front <- factor(gorilla$Q2.3, levels = c("가", "나", "다"), labels = c("맨 위의 비행접시", "중간 위치 비행접시", "맨 아래 비행접시"))
ames_room <- factor(gorilla$Q3, levels = c("가", "나"), labels = c("정상적인 방이다", "아니다"))
reading_1 <- factor(gorilla$Q4.1, levels = c("수영", "누영"))
reading_2 <- factor(gorilla$Q4.2, levels = c("미특보살", "미륵보살"))
reading_3 <- factor(gorilla$Q4.3, levels = c("248", "2나8"))
reading_4 <- factor(gorilla$Q4.4, levels = c("너와나", "너와4"))
reading_5 <- factor(gorilla$Q4.5, levels = c("새농어촌건설운동", "애농어촌건설운동"), labels = c("새농어촌건설운동", "모르겠다"))
reading_6 <- factor(gorilla$Q4.6, levels = c("TAE CAT", "TAE CHT", "THE CAT", "THE CHT"))
pass_1.1 <- gorilla$Q5.1
pass_1.2 <- factor(gorilla$Q5.2, levels = c("가", "나"), labels = c("보았다", "못 보았다"))
pass_2.1 <- gorilla$Q6.1
pass_2.2 <- factor(gorilla$Q6.2, levels = c("가", "나"), labels = c("보았다", "못 보았다"))
pass_2.3 <- factor(gorilla$Q6.3, levels = c("가", "나"), labels = c("보았다", "못 보았다"))
pass_2.4 <- factor(gorilla$Q6.4, levels = c("가", "나"), labels = c("보았다", "못 보았다"))
door_study <- factor(gorilla$Q7, levels = c("가", "나"), labels = c("알아차렸다", "몰랐다"))
stereotype <- factor(gorilla$Q8, levels = c("가", "나"), labels = c("무시한다", "팻말에 따른다"))
prejudice <- factor(gorilla$Q9, levels = c("가", "나", "다"), labels = c("동등하게", "백인 우호", "동남아인 우호"))
chocolate <- gorilla$Q10
ls()
```

### 응답 결과

```{r, responses, echo = FALSE}
pander(table(wrong_diff), caption = "이 사람들은 나하고 생각이")
pander(table(monkey_panda_banana), caption = "두 개를 고른다면?")
pander(table(still_happy), caption = "여전히 행복한가요?")
pander(table(which_one_in_front), caption = "어느 것이 앞쪽에 있나요?")
pander(table(monkey_panda_banana, which_one_in_front), caption = "원숭이-바나나-팬더 vs 어느 것이 앞쪽에 있나요?")
pander(table(ames_room), caption = "정상적인 방으로 보이나요?")
pander(table(reading_1), caption = "이 단어는?")
pander(table(reading_2), caption = "이것은?")
pander(table(reading_3), caption = "이 문구는?")
pander(table(reading_4), caption = "이 문구는?")
pander(table(reading_5), caption = "이 간판 문구는?")
pander(table(reading_6), caption = "이 영어자막은?")
pander(summary(pass_1.1), caption = "흰 셔츠 팀의 패스 성공횟수는?")
pander(table(pass_1.2), caption = "고릴라 본 사람?")
pander(summary(pass_2.1), caption = "흰 셔츠 팀의 패스 성공횟수는?")
pander(table(pass_2.2), caption = "고릴라 본 사람?")
pander(table(pass_2.3), caption = "커튼 색 바뀐 것 본 사람?")
pander(table(pass_2.4), caption = "선수 나가는 것 본 사람?")
pander(table(door_study), caption = "처음부터 알아차렸나요?")
pander(table(stereotype), caption = "나라면?")
pander(table(prejudice), caption = "How do I go to COEX?")
pander(summary(chocolate), caption = "몇 개나 줄 거예요?")
```


### 자료 갈무리

```{r, save.image, echo = FALSE}
save.image("gorilla_0601.rda")
```
