---
title: "Invisible Gorilla 201701"
author: "coop711"
date: "2017-05-29"
output: html_document
---

<!--
### Data

#### Read In

```{r, library and read, echo = FALSE, message = FALSE, results = 'hide'}
library(xlsx)
library(pander)
library(ggplot2)
panderOptions("table.split.table", Inf)
options(digits=3)
gorilla <- read.xlsx("../data/gorilla170529.xlsx", 1, startRow = 2, endRow = 161, header = TRUE, colIndex = c(3:7, 9:31), colClasses = c(rep("character", 27), "numeric"), stringsAsFactors = FALSE)
# load("./gorilla_0601.rda")
str(gorilla)
```

#### Management

```{r, data restructuring, echo = FALSE, results='hide'}
names(gorilla) <- c("dept", "id", "name", "year", "e.mail", "cell.no", "group", "Q1", "Q2.1", "Q2.2", "Q2.3", "Q3", "Q4.1", "Q4.2", "Q4.3", "Q4.4", "Q4.5", "Q4.6", "Q5.1", "Q5.2", "Q6.1", "Q6.2", "Q6.3", "Q6.4", "Q7", "Q8", "Q9", "Q10")
gorilla$dept <- factor(gorilla$dept)
gorilla$year <- factor(gorilla$year)
gorilla$group <- factor(gorilla$group, levels = c("Red", "Black"))
str(gorilla)
wrong_diff <- factor(gorilla$Q1, levels = c("가", "나"), labels = c("틀리다", "다르다"))
monkey_panda_banana <- factor(gorilla$Q2.1, levels = c("가", "나", "다"), labels = c("원숭이와 바나나", "원숭이와 팬더", "팬더와 바나나"))
still_happy <- factor(gorilla$Q2.2, levels = c("가", "나"), labels = c("행복해 보인다", "행복해 보이지 않는다"))
which_one_in_front <- factor(gorilla$Q2.3, levels = c("가", "나", "다"), labels = c("맨 위의 비행접시", "중간 위치 비행접시", "맨 아래 비행접시"))
gorilla$Q3.2 <- ifelse(gorilla$Q3 == "가", "가(평범한 방)", ifelse(gorilla$Q3 == "나", "나(닮은 창 둘)", ifelse(gorilla$Q3 == "다", "다(키큰 왼편 여자)", gorilla$Q3)))
levels.Q3.2 <- c("가,나,다", "가,나", "나,다", "가(평범한 방)", "나(닮은 창 둘)", "다(키큰 우측 여자)") 
ames_room <- factor(gorilla$Q3.2, levels = levels.Q3.2)
reading_1 <- factor(gorilla$Q4.1, levels = c("수영", "누영"))
reading_2 <- factor(gorilla$Q4.2, levels = c("미특보살", "미륵보살"))
reading_3 <- factor(gorilla$Q4.3, levels = c("248", "2나8"))
reading_4 <- factor(gorilla$Q4.4, levels = c("너와나", "너와4"))
reading_5 <- factor(gorilla$Q4.5, levels = c("새농어촌건설운동", "애농어촌건설운동"), labels = c("새농어촌건설운동", "모르겠다"))
reading_6 <- factor(gorilla$Q4.6, levels = c("TAE CAT", "TAE CHT", "THE CAT", "THE CHT"))
pass_1.1 <- factor(gorilla$Q5.1, levels = c("가", "나", "다", "라", "마"), labels = c(12:16))
pass_1.2 <- factor(gorilla$Q5.2, levels = c("가", "나"), labels = c("보았다", "못 보았다"))
pass_2.1 <- factor(gorilla$Q6.1, levels = c("가", "나", "다", "라", "마"), labels = c(13:17))
pass_2.2 <- factor(gorilla$Q6.2, levels = c("가", "나"), labels = c("보았다", "못 보았다"))
pass_2.3 <- factor(gorilla$Q6.3, levels = c("가", "나"), labels = c("보았다", "못 보았다"))
pass_2.4 <- factor(gorilla$Q6.4, levels = c("가", "나"), labels = c("보았다", "못 보았다"))
door_study <- factor(gorilla$Q7, levels = c("가", "나"), labels = c("알아차렸다", "몰랐다"))
stereotype <- factor(gorilla$Q8, levels = c("가", "나"), labels = c("무시한다", "팻말에 따른다"))
prejudice <- factor(gorilla$Q9, levels = c("가", "나", "다"), labels = c("동등하게", "백인 우호", "동남아인 우호"))
chocolate <- factor(gorilla$Q10, levels = c(0:10))
ls()
```

```{r, function}
paste.p <- function(tbl) {
t(matrix(paste(format(prop.table(tbl)*100, digits = 2, nsmall = 1), "%", sep = ""), nrow = dim(tbl)[1], dimnames = dimnames(tbl)))
}
dump(list = "paste.p", file = "./paste_p.R")
```

-->

## 응답 결과

### 다르다와 틀리다

```{r, diff and wrong, echo = FALSE}
source("./paste_p.R")
tbl.wrong_diff <- table(wrong_diff)
pander(tbl.wrong_diff, caption = "이 사람들은 나하고 생각이")
pander(paste.p(tbl.wrong_diff))
# pander(t(matrix(paste(format(prop.table(tbl.wrong_diff)*100, digits = 2, nsmall = 1), "%", sep = ""), nrow = dim(tbl.wrong_diff)[1], dimnames = dimnames(tbl.wrong_diff))))
```

### 동과 서

```{r, East vs West, echo = FALSE}
tbl.monkey_panda_banana <- table(monkey_panda_banana)
pander(tbl.monkey_panda_banana, caption = "두 개를 고른다면?")
pander(paste.p(tbl.monkey_panda_banana))
# pander(t(matrix(paste(format(prop.table(tbl.monkey_panda_banana)*100, digits = 2, nsmall = 1), "%", sep = ""), nrow = dim(tbl.monkey_panda_banana)[1], dimnames = dimnames(tbl.monkey_panda_banana))))
tbl.still_happy <- table(still_happy)
pander(tbl.still_happy, caption = "여전히 행복한가요?")
pander(paste.p(tbl.still_happy))
# pander(t(matrix(paste(format(prop.table(tbl.still_happy)*100, digits = 2, nsmall = 1), "%", sep = ""), nrow = dim(tbl.still_happy)[1], dimnames = dimnames(tbl.still_happy))))
tbl.which_one_in_front <- table(which_one_in_front)
pander(tbl.which_one_in_front, caption = "어느 것이 앞쪽에 있나요?")
pander(paste.p(tbl.which_one_in_front))
# pander(t(matrix(paste(format(prop.table(tbl.which_one_in_front)*100, digits = 2, nsmall = 1), "%", sep = ""), nrow = dim(tbl.which_one_in_front)[1], dimnames = dimnames(tbl.which_one_in_front))))
tbl.monkey_panda_banana.which_one_in_front <- table(monkey_panda_banana, which_one_in_front)
pander(tbl.monkey_panda_banana.which_one_in_front, caption = "원숭이-바나나-팬더 vs 어느 것이 앞쪽에 있나요?")
pander(paste.p(tbl.monkey_panda_banana.which_one_in_front))
# pander(t(matrix(paste(format(prop.table(tbl.monkey_panda_banana.which_one_in_front)*100, digits = 2, nsmall = 1), "%", sep = ""), nrow = dim(tbl.monkey_panda_banana.which_one_in_front)[1], dimnames = dimnames(tbl.monkey_panda_banana.which_one_in_front))))
```

### 시각의 한계

```{r, ames room, echo = FALSE}
pander(table(ames_room), caption = "정상적인 방으로 보이나요?")
```

### 손글씨 읽기

```{r, handwriting, echo = FALSE}
tbl.reading_1 <- table(reading_1)
pander(tbl.reading_1, caption = "이 단어는?")
pander(paste.p(tbl.reading_1))
tbl.reading_2 <- table(reading_2)
pander(tbl.reading_2, caption = "이것은?")
pander(paste.p(tbl.reading_2))
tbl.reading_3 <- table(reading_3)
pander(tbl.reading_3, caption = "이 문구는?")
pander(paste.p(tbl.reading_3))
tbl.reading_4 <- table(reading_4)
pander(tbl.reading_4, caption = "이 문구는?")
pander(paste.p(tbl.reading_4))
tbl.reading_5 <- table(reading_5)
pander(tbl.reading_5, caption = "이 간판 문구는?")
pander(paste.p(tbl.reading_5))
tbl.reading_6 <- table(reading_6)
pander(tbl.reading_6, caption = "이 영어자막은?")
pander(paste.p(tbl.reading_6))
```

### Selective Attention Test

```{r, SAT, echo = FALSE}
pander(table(pass_1.1), caption = "흰 셔츠 팀의 패스 성공횟수는?")
tbl.pass_1.2 <- table(pass_1.2)
pander(tbl.pass_1.2, caption = "고릴라 본 사람?")
pander(t(matrix(paste(format(prop.table(tbl.pass_1.2)*100, digits = 2, nsmall = 1), "%", sep = ""), nrow = dim(tbl.pass_1.2)[1], dimnames = dimnames(tbl.pass_1.2))))
```

### Monkey Business Illusion

```{r, MBI, echo = FALSE}
pander(table(pass_2.1), caption = "흰 셔츠 팀의 패스 성공횟수는?")
tbl.pass_2.2 <- table(pass_2.2)
pander(tbl.pass_2.2, caption = "고릴라 본 사람?")
pander(t(matrix(paste(format(prop.table(tbl.pass_2.2)*100, digits = 2, nsmall = 1), "%", sep = ""), nrow = dim(tbl.pass_2.2)[1], dimnames = dimnames(tbl.pass_2.2))))
tbl.pass_2.3 <- table(pass_2.3)
pander(tbl.pass_2.3, caption = "커튼 색 바뀐 것 본 사람?")
pander(t(matrix(paste(format(prop.table(tbl.pass_2.3)*100, digits = 2, nsmall = 1), "%", sep = ""), nrow = dim(tbl.pass_2.3)[1], dimnames = dimnames(tbl.pass_2.3))))
tbl.pass_2.4 <- table(pass_2.4)
pander(tbl.pass_2.4, caption = "선수 나가는 것 본 사람?")
pander(t(matrix(paste(format(prop.table(tbl.pass_2.4)*100, digits = 2, nsmall = 1), "%", sep = ""), nrow = dim(tbl.pass_2.4)[1], dimnames = dimnames(tbl.pass_2.4))))
```

#### Door Study

```{r, door study, echo = FALSE}
tbl.door_study <- table(door_study)
pander(tbl.door_study, caption = "처음부터 알아차렸나요?")
pander(t(matrix(paste(format(prop.table(tbl.door_study)*100, digits = 2, nsmall = 1), "%", sep = ""), nrow = dim(tbl.door_study)[1], dimnames = dimnames(tbl.door_study))))
```

#### 고정관념

```{r, stereotypes, echo = FALSE}
tbl.stereotype <- table(stereotype)
pander(tbl.stereotype, caption = "나라면?")
pander(t(matrix(paste(format(prop.table(tbl.stereotype)*100, digits = 2, nsmall = 1), "%", sep = ""), nrow = dim(tbl.stereotype)[1], dimnames = dimnames(tbl.stereotype))))
```

#### 편견

```{r, prejudices, echo = FALSE}
tbl.prejudice <- table(prejudice)
pander(tbl.prejudice, caption = "How do I go to COEX?")
pander(t(matrix(paste(format(prop.table(tbl.prejudice)*100, digits = 2, nsmall = 1), "%", sep = ""), nrow = dim(tbl.prejudice)[1], dimnames = dimnames(tbl.prejudice))))
```

#### Chocolate 실험

```{r, chocolate, echo = FALSE}
# pander(summary(chocolate), caption = "몇 개나 줄 거예요?")
pander(table(chocolate), caption = "몇 개나 줄 거예요?")
pander(summary(gorilla$Q10), caption = "기초통계")
```

<!--
### 자료 갈무리

```{r, save.image, echo = FALSE}
save.image("gorilla_170529.RData")
```
-->