---
title: "Quiz 160926"
author: "coop711"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# install.packages("pander", repos = "https://cran.rstudio.com")
# install.packages("xlsx", repos = "https://cran.rstudio.com")
library(xlsx)
library(pander)
library(knitr)
panderOptions('table.split.table', Inf)
panderOptions('table.alignment.rownames', 'left')
panderOptions('table.alignment.default', 'right')
options(width=180)
```

```{r, data, echo = FALSE, results = 'hide'}
quiz0926 <- read.xlsx("../data/quiz0926.xlsx", 1, startRow = 2, endRow = 102, colIndex = c(3:7, 9:14), colClasses = c(rep("character", 11)), stringsAsFactors=FALSE)
str(quiz0926)
names(quiz0926) <- c("dept", "id", "name", "year", "e.mail", "cell.no", "Q1", "Q2", "Q3", "Q4", "group")
quiz0926$dept <- factor(quiz0926$dept)
quiz0926$year <- factor(quiz0926$year)
quiz0926$group <- factor(quiz0926$group, levels = c("Red", "Black"))
quiz0926$Q1 <- factor(quiz0926$Q1, levels = c("가", "나", "다", "라", "무응답"), labels = c("공평", "무난", "철저", "균일", "무응답"))
quiz0926$Q2 <- factor(quiz0926$Q2, levels = c("가", "나", "다", "라", "무응답"), labels = c("Selection Bias", "Response Bias", "Non-response Bias", "Panel Bias", "무응답"))
quiz0926$Q3 <- factor(quiz0926$Q3, levels = c("가", "나", "다", "라", "무응답"), labels = c("다단계집락추출법", "할당법", "단순랜덤추출법", "RDD", "무응답"))
quiz0926$Q4 <- factor(quiz0926$Q4, levels = c("1", "2", "3", "9", "무응답"))
quiz0926$Q4.2 <- quiz0926$Q4
levels(quiz0926$Q4.2[quiz0926$group == "Black"]) <- c("2", "1", "3", "9", "무응답")
levels(quiz0926$Q4.2) <- c("잘하고 있다", "잘못하고 있다", "어느 쪽도 아니다", "모르겠다", "무응답")
str(quiz0926)
```

```{r, randomization, echo = FALSE, results = 'hide'}
pander(summary(quiz0926))
```

### 퀴즈 응답 비교

#### 통계학의 기본원리

##### 공평하게 추출하면 ...

```{r, fairness, echo = FALSE}
Q1.tbl.am <- addmargins(table(quiz0926$group, quiz0926$Q1, exclude = NULL), margin = 1)
colnames(Q1.tbl.am)[6] <- "결석"
rownames(Q1.tbl.am)[4] <- "계"
pander(Q1.tbl.am[-3, ], caption = "통계학의 기본원리")
```

##### 공평하게 추출하면 ... (%)

```{r, fairness in percentage, echo = FALSE}
pander(round(prop.table(Q1.tbl.am, margin = 1)[4, ]*100, digits = 1))
```

#### 리터러리 다이제스트의 실패

##### Selection Bias

```{r, Selection Bias, echo = FALSE}
Q2.tbl.am <- addmargins(table(quiz0926$group, quiz0926$Q2, exclude = NULL), margin = 1)
colnames(Q2.tbl.am)[6] <- "결석"
rownames(Q2.tbl.am)[4] <- "계"
pander(Q2.tbl.am[-3, ])
```

##### Selection Bias (%)

```{r, Selection Bias in percentage, echo = FALSE}
pander(round(prop.table(Q2.tbl.am, margin = 1)[4,]*100, digits=1), caption = "리터러리 다이제스트의 실패원인?")
```

#### 1948년, 여론조사가 듀이를 당선시킨 해

##### 할당법의 문제점

```{r, quota sampling, echo = FALSE}
Q3.tbl.am <- addmargins(table(quiz0926$group, quiz0926$Q3, exclude = NULL), margin = 1)
colnames(Q3.tbl.am)[6] <- "결석"
rownames(Q3.tbl.am)[4] <- "계"
pander(Q3.tbl.am[-3, ], caption = "여론조사가 듀이를 당선시키다")
```

##### 할당법의 문제점(%)

```{r, quota sampling in percentage, echo = FALSE}
pander(round(prop.table(Q3.tbl.am, margin=1)[4,]*100, digits = 1), caption = "문해력이 낮으면?")
```

### 국정수행 지지도 파악

#### 질문지 답 문항 순서의 영향

##### 긍정 답안(잘하고 있다)가 먼저 나오는지(Red), 부정 답안(잘못하고 있다)가 먼저 나오는지(Black)에 따라 응답이 달라질 것으로, 즉 먼저 나온 답안에 응답이 높게 나올 것으로 기대하였으나, 응답은 반대로 나왔음.

```{r, vote attitude, echo = FALSE}
poll.tbl.e <- addmargins(table(quiz0926$group, quiz0926$Q4.2, exclude = NULL), margin = 1)
colnames(poll.tbl.e)[6] <- "결석"
rownames(poll.tbl.e)[4] <- "계"
pander(poll.tbl.e[-3, ], caption = "국정수행지지도")
```

##### % 비교.  

```{r, vote attitude in percentage, echo = FALSE}
merge.tbl <- table(quiz0926$group, quiz0926$Q4.2)
merge.tbl.am <- addmargins(table(quiz0926$group, quiz0926$Q4.2), margin = 1)
pander(round(prop.table(merge.tbl, margin = 1)*100, digits = 1))
```

#### 합산

```{r, percentage in sum, echo = FALSE}
pander(round(prop.table(merge.tbl.am[3, ])*100, digits = 1))
```

```{r, save, echo = FALSE}
#save.image("../R/quiz0926.rda")
```