---
title: "Quiz 160905"
author: "coop711"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# install.packages("pander", repos = "https://cran.rstudio.com")
# install.packages("xlsx", repos = "https://cran.rstudio.com")
library(xlsx)
library(pander)
library(knitr)
panderOptions('table.split.table', Inf)
panderOptions('table.alignment.rownames', 'left')
panderOptions('table.alignment.default', 'right')
options(width=180)
```

```{r, data, echo = FALSE, results = 'hide'}
quiz0905 <- read.xlsx("../data/quiz0905.xlsx", 1, startRow = 2, endRow = 101, colIndex = c(3:7, 9:14), colClasses=c(rep("character", 11)), stringsAsFactors=FALSE)
str(quiz0905)
names(quiz0905) <- c("dept", "id", "name", "year", "e.mail", "cell.no", "Q1", "Q2", "Q3", "Q4", "group")
quiz0905$dept <- factor(quiz0905$dept)
quiz0905$year <- factor(quiz0905$year)
quiz0905$group <- factor(quiz0905$group, levels = c("Red", "Black"))
quiz0905$Q1 <- factor(quiz0905$Q1, levels = c("가", "나", "다", "라", "마"), labels = c("9:1", "8:2", "7:3", "6:4", "5:5"))
quiz0905$Q2 <- factor(quiz0905$Q2, levels = c("가", "나", "다", "라", "마"), labels = c("10%", "30%", "50%", "70%", "90%"))
quiz0905$Q3 <- factor(quiz0905$Q3, levels = c("가", "나", "다", "라", "마"), labels = c("7:3", "6:4", "5:5", "4:6", "3:7"))
quiz0905$Q4 <- factor(quiz0905$Q4, levels = c("가", "나", "다"), labels = c("찬성 입장", "반대 입장", "모름/무응답"))
quiz0905$Q4.2 <- quiz0905$Q4
levels(quiz0905$Q4.2)
levels(quiz0905$Q4.2) <- c("찬성", "반대", "모름/무응답")
str(quiz0905)
```

```{r, summary, echo = FALSE, results = 'hide'}
pander(summary(quiz0905))
```

### 퀴즈 응답 비교

#### 우리나라 국세와 지방세 배분비율

##### 국세와 지방세

```{r, National and Local tax, echo = FALSE}
Q1.tbl.am <- addmargins(table(quiz0905$group, quiz0905$Q1, exclude = NULL), margin = 1)
colnames(Q1.tbl.am)[6] <- "결석"
rownames(Q1.tbl.am)[4] <- "계"
pander(Q1.tbl.am)
```

##### 국세와 지방세(%)

```{r, National and Local tax in percentage, echo = FALSE}
pander(round(prop.table(Q1.tbl.am, margin = 1)[4, ]*100, digits = 2))
```

#### 공법도입에 대한 대신들의 찬성율

##### 공법도입과 대신들(집계표)

```{r, tax law and cabinets, echo = FALSE}
Q2.tbl.am <- addmargins(table(quiz0905$group, quiz0905$Q2, exclude = NULL), margin = 1)
colnames(Q2.tbl.am)[6] <- "결석"
rownames(Q2.tbl.am)[4] <- "계"
pander(Q2.tbl.am)
```

##### 공법도입과 대신들(%)

```{r, tax law and cabinets in percentage, echo = FALSE}
pander(round(prop.table(Q2.tbl.am, margin=1)[4,]*100, digits = 2), caption = "공법도입과 대신들의 찬성률")
```

#### 공법도입과 품관촌민들의 찬반

##### 품관촌민들의 찬반(집계표)

```{r, tax law and laymen, echo = FALSE}
Q3.tbl.am <-addmargins(table(quiz0905$group, quiz0905$Q3, exclude = NULL), margin = 1)
colnames(Q3.tbl.am)[6] <- "결석"
rownames(Q3.tbl.am)[4] <- "계"
pander(Q3.tbl.am)
```

##### 품관촌민들의 찬반(%)

```{r, tax law and laymen in percentage, echo = FALSE}
pander(round(prop.table(Q3.tbl.am, margin = 1)[4, ]*100, digits = 1), caption = "품관촌민들의 찬반")
```

### 테러방지법 찬반

#### 테러방지법 찬반

##### 집계표. 찬반 어느 쪽에 부연설명을 하였는가(Red는 찬성 쪽에 부연설명, Black은 반대 쪽에 부연설명)에 따라 찬반에 영향. 

```{r, anti-terror law, echo = FALSE}
thaad.tbl.e <- table(quiz0905$group, quiz0905$Q4, exclude = NULL)
colnames(thaad.tbl.e)[4] <- "결석"
pander(thaad.tbl.e, caption="테러방지법")
# pander(table(quiz0905$group, quiz0905$Q4.2, exclude = NULL), caption="테러방지법")
```

##### % 비교.  

```{r, anti-terror law in percentage, echo = FALSE}
thaad.tbl <- table(quiz0905$group, quiz0905$Q4)
# thaad.tbl.2 <- table(quiz0905$group, quiz0905$Q4.2)
# pander(round(prop.table(thaad.tbl, margin = 1)*100, digits = 1), caption="테러방지법(단위, %)")
pander(round(prop.table(thaad.tbl, margin = 1)*100, digits = 1))
# pander(round(prop.table(thaad.tbl.2, margin = 1)*100, digits = 1), caption = "테러방지법(단위, %)")
```

```{r, save, echo = FALSE}
#save.image("../R/quiz0905.rda")
```