---
title: "Quiz 170315"
author: "coop711"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# install.packages("pander", repos = "https://cran.rstudio.com")
# install.packages("xlsx", repos = "https://cran.rstudio.com")
library(xlsx)
library(pander)
library(knitr)
panderOptions('table.split.table', Inf)
panderOptions('table.alignment.rownames', 'left')
panderOptions('table.alignment.default', 'right')
options(width=180)
```

```{r, data, echo = FALSE, results = 'hide'}
quiz0315 <- read.xlsx("../data/quiz0315.xlsx", 1, startRow = 2, endRow = 162, colIndex = c(3:7, 9:15), colClasses = c(rep("character", 12)), stringsAsFactors = FALSE)
str(quiz0315)
names(quiz0315) <- c("dept", "id", "name", "year", "e.mail", "cell.no", "Q1", "Q2", "Q3", "Q4", "group", "group.roll")
quiz0315$dept <- factor(quiz0315$dept)
quiz0315$year <- factor(quiz0315$year)
quiz0315$group <- factor(quiz0315$group, levels = c("Red", "Black"))
quiz0315$group.roll <- factor(quiz0315$group.roll, levels = c("Red", "Black"))
quiz0315$Q1 <- factor(quiz0315$Q1, levels = c("가", "나", "다", "라"), labels = c("1/10", "1/15", "1/20", "1/30"))
quiz0315$Q2 <- factor(quiz0315$Q2, levels = c("가", "나", "다", "라"), labels = c("15만호", "20만호", "44만호", "130만호"))
quiz0315$Q3 <- factor(quiz0315$Q3, levels = c("가", "나", "다", "라", "마", "무응답"), labels = c("경기", "평안", "전라", "경상", "충청", "무응답"))
na.group <- is.na(quiz0315$group)
quiz0315$group[na.group] <- quiz0315$group.roll[na.group]
quiz0315$Q4[quiz0315$group == "Red"]
(Q4.R <- quiz0315$Q4[quiz0315$group == "Red"])
(Q4.Rf <- factor(Q4.R, levels = c("가", "나", "다"), labels = c("잘못한 결정", "잘한 결정", "모르겠다"), exclude = NA))
quiz0315$Q4[quiz0315$group == "Black"]
(Q4.B <- quiz0315$Q4[quiz0315$group == "Black"])
(Q4.Bf <- factor(Q4.B, levels = c("가", "나", "다", "라", "마", "바"), labels = c("황교안", "이재명", "안희정", "안철수", "문재인", "기타/없다"), exclude = NA))
Q4.Rf
Q4.Bf
str(quiz0315)
```

```{r, randomization, echo = FALSE, results = 'hide'}
pander(summary(quiz0315))
```

### 퀴즈 응답 비교

#### 공법

##### 기본세율

```{r, National and Local tax, echo = FALSE}
Q1.tbl.am <- addmargins(table(quiz0315$group, quiz0315$Q1, exclude = NULL), margin = 1)
Q1.tbl.am
colnames(Q1.tbl.am)[5] <- "결석"
rownames(Q1.tbl.am)[3] <- "계"
pander(Q1.tbl.am[-3, ])
```

##### 기본세율(%)

```{r, National and Local tax in percentage, echo = FALSE}
pander(round(prop.table(Q1.tbl.am, margin=1)[3,]*100, digits=1))
```

#### 1423년 조선시대 호구와 인구

##### 호구와 인구

```{r, tax law and cabinets, echo = FALSE}
Q2.tbl.am <- addmargins(table(quiz0315$group, quiz0315$Q2, exclude = NULL), margin = 1)
colnames(Q2.tbl.am)[5] <- "결석"
rownames(Q2.tbl.am)[3] <- "계"
pander(Q2.tbl.am[-3, ])
```

##### 호구와 인구(%)

```{r, tax law and cabinets in percentage, echo = FALSE}
pander(round(prop.table(Q2.tbl.am, margin = 1)[3,]*100, digits=1), caption="공법도입과 대신들")
```

#### 지방관료와 품관촌민

##### 찬반이 반대인 곳(집계표)

```{r, tax law and laymen, echo = FALSE}
Q3.tbl.am <- addmargins(table(quiz0315$group, quiz0315$Q3, exclude = NULL), margin = 1)
colnames(Q3.tbl.am)[7] <- "결석"
rownames(Q3.tbl.am)[3] <- "계"
pander(Q3.tbl.am[-3, ])
```

##### 찬반이 반대인 곳(%)

```{r, tax law and laymen in percentage, echo = FALSE}
pander(round(prop.table(Q3.tbl.am, margin=1)[3,]*100, digits=1), caption="품관촌민들의 찬반")
```

### 탄핵 결정과 대선 후보 지지도

#### Red : 탄핵 결정에 대한 판단

##### 표

```{r, impeachment, echo = FALSE}
tbl.R <- table(Q4.Rf)
# colnames(tbl.R)[4] <- "결석"
tbl.R.m <- t(as.matrix(tbl.R))
tbl.R.m[, 2] <- 47
pander(tbl.R.m, caption = "탄핵결정 판단")
```

##### %

```{r, impeachment in percentage, echo = FALSE}
prop.tbl.R <- t(as.matrix(round(prop.table(tbl.R)*100, digits = 1)))
prop.tbl.R[, c(1, 3)] <- 0
pander(prop.tbl.R)
# pander(round(prop.table(tbl.R, margin = 1)*100, digits = 1))
```

#### Black : 대선 후보 지지도

##### 표

```{r, poll, echo = FALSE}
tbl.B <- table(Q4.Bf)
# colnames(tbl.B)[7] <- "결석"
pander(t(as.matrix(tbl.B)), caption = "대선후보 지지도")
```

##### %

```{r, poll in percentage, echo = FALSE}
prop.tbl.B <- t(as.matrix(round(prop.table(tbl.B)*100, digits = 1)))
pander(prop.tbl.B)
# pander(t(as.matrix(round(prop.table(tbl.B)*100, digits = 1))))
# pander(round(prop.table(tbl.B, margin = 1)*100, digits = 1))
```

```{r, save, echo = FALSE}
#save.image("../R/quiz0315.rda")
```