---
title: "Quiz 161102"
author: "coop711"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# install.packages("pander", repos = "https://cran.rstudio.com")
# install.packages("xlsx", repos = "https://cran.rstudio.com")
library(xlsx)
library(pander)
library(knitr)
panderOptions('table.split.table', Inf)
panderOptions('table.alignment.rownames', 'left')
panderOptions('table.alignment.default', 'right')
options(width = 180)
```

```{r, data, echo = FALSE, results = 'hide'}
quiz1102 <- read.xlsx("../data/quiz1102.xlsx", 1, startRow = 2, endRow = 97, colIndex = c(3:7, 9:14), colClasses = c(rep("character", 11)), stringsAsFactors = FALSE)
str(quiz1102)
names(quiz1102) <- c("dept", "id", "name", "year", "e.mail", "cell.no", "Q1", "Q2", "Q3", "Q4", "group")
quiz1102$dept <- factor(quiz1102$dept)
quiz1102$year <- factor(quiz1102$year)
quiz1102$group <- factor(quiz1102$group, levels = c("Red", "Black"))
quiz1102$Q1 <- factor(quiz1102$Q1, levels = c("가", "나", "다", "라"), labels = c("생산성 향상 < 임금 향상", "고소득층 소득 > 중산층 이하 소득", "중산층 이하 소득 > 고소득층 소득", "평균 임금 증가율 < 중위 임금 증가율"))
quiz1102$Q2 <- factor(quiz1102$Q2, levels = c("가", "나", "다", "라"), labels = c("10억", "20억", "25억", "30억"))
quiz1102$Q3 <- factor(quiz1102$Q3, levels = c("가", "나", "다", "라"), labels = c("100%", "75%", "50%", "25%"))
quiz1102$Q4 <- factor(quiz1102$Q4, levels = c("가", "나", "다", "라", "ㅁㅏ"), labels = c("무상", "100만원", "200만원", "500만원", "1,000만원"))
# quiz1102$Q4.2 <- quiz1102$Q4
# quiz1102$Q4.2[quiz1102$group == "Black" & quiz1102$Q4.2 == "가"] <- "아니다"
# quiz1102$Q4.2[quiz1102$group == "Black" & quiz1102$Q4.2 == "나"] <- "하야"
# quiz1102$Q4.2[quiz1102$group == "Black" & quiz1102$Q4.2 == "다"] <- "탄핵"
# quiz1102$Q4.2[quiz1102$group == "Black" & quiz1102$Q4.2 == "라"] <- "모르겠다"
# quiz1102$Q4.2[quiz1102$group == "Black" & quiz1102$Q4.2 == "조퇴"] <- "조퇴"
# quiz1102$Q4.2[quiz1102$group == "Red" & quiz1102$Q4.2 == "가"] <- "탄핵"
# quiz1102$Q4.2[quiz1102$group == "Red" & quiz1102$Q4.2 == "나"] <- "하야"
# quiz1102$Q4.2[quiz1102$group == "Red" & quiz1102$Q4.2 == "다"] <- "아니다"
# quiz1102$Q4.2[quiz1102$group == "Red" & quiz1102$Q4.2 == "라"] <- "모르겠다"
# quiz1102$Q4.2[quiz1102$group == "Red" & quiz1102$Q4.2 == "조퇴"] <- "조퇴"
# quiz1102$Q4.2 <- factor(quiz1102$Q4.2, levels = c("탄핵", "하야", "아니다", "모르겠다", "조퇴"))
str(quiz1102)
```

```{r, randomization, echo = FALSE, results = 'hide'}
pander(summary(quiz1102))
```

### 퀴즈 응답 비교

#### 생산성과 평균 및 중위 임금

##### 평균 임금과 중위 임금

```{r, productivity vs wage, echo = FALSE}
Q1.tbl.am <- addmargins(table(quiz1102$group, quiz1102$Q1, exclude = NULL), margin = 1)
colnames(Q1.tbl.am)[5] <- "결석"
rownames(Q1.tbl.am)[4] <- "계"
pander(Q1.tbl.am[-3, ])
```

##### 평균임금과 중위 임금 (%)

```{r, productivity vs wage in percentage, echo = FALSE}
pander(round(prop.table(Q1.tbl.am, margin = 1)[4, ]*100, digits = 1))
```

#### LM3

##### LM3의 의미

```{r, LM3, echo = FALSE}
Q2.tbl.am <- addmargins(table(quiz1102$group, quiz1102$Q2, exclude = NULL), margin = 1)
colnames(Q2.tbl.am)[5] <- "결석"
rownames(Q2.tbl.am)[4] <- "계"
pander(Q2.tbl.am[-3, ])
```

##### 

```{r, LM3 in percentage, echo = FALSE}
pander(round(prop.table(Q2.tbl.am, margin = 1)[4,]*100, digits=1))
```

#### 식량자급률

##### 우리나라 식량자급률 수준

```{r, MTR, echo = FALSE}
Q3.tbl.am <- addmargins(table(quiz1102$group, quiz1102$Q3, exclude = NULL), margin = 1)
colnames(Q3.tbl.am)[5] <- "결석"
rownames(Q3.tbl.am)[4] <- "계"
pander(Q3.tbl.am[-3, ])
```

##### 우리나라 식량자급률 수준 (%)

```{r, MTRE in percentage, echo = FALSE}
pander(round(prop.table(Q3.tbl.am, margin = 1)[4,]*100, digits = 1))
```

#### 국공립대 등록금 국제 비교

이 질문은 THAAD배치 질문에서와 같이 배경 설명이 응답에 많은 영향을 미친다는 것을 보여줍니다. 국공립대학의 등록금이 무상인 나라들을 소개한 Red군에서는 적정 수준이 "무상"이라고 응답한 비율이 34%나 되는 반면에 국공립대학의 등록금이 우리나라보다 높거나 대등한 나라들의 예를 먼저 들고 적정 수준을 물어본 경우(Black)에는 "무상"에 응답한 비율이 4.4%에 불과한 것을 알 수 있습니다.

##### 국공립대 등록금의 적정 수준

```{r, college tuition, echo = FALSE}
Q4.tbl.am <- addmargins(table(quiz1102$group, quiz1102$Q4, exclude = NULL), margin = 1)
colnames(Q4.tbl.am)[6] <- "결석"
rownames(Q4.tbl.am)[4] <- "계"
pander(Q4.tbl.am[-3, ])
```

##### 국공립대 등록금의 적정 수준 (%)

```{r, college tuition in percentage, echo = FALSE}
pander(round(prop.table(Q4.tbl.am, margin = 1)[-(3:4), ]*100, digits = 1))
```

<!--
### 국정농단

#### 탄핵, 하야?

##### 

```{r, Soonsil, echo = FALSE}
# Q4.tbl.e <- table(quiz1102$group, quiz1102$Q4.2, exclude = NULL)
# Q4.tbl.am <- addmargins(Q4.tbl.e, margin = 1)
# colnames(Q4.tbl.am)[6] <- "결석"
# rownames(Q4.tbl.am)[4] <- "계"
# pander(Q4.tbl.am[-3, ])
```

##### % 비교.  

```{r, Soonsil in percentage, echo = FALSE}
# Q4.tbl <- table(quiz1102$group, quiz1102$Q4.2)[, 1:4]
# pander(round(prop.table(Q4.tbl, margin = 1)*100, digits = 1))
```

#### 합산(%)

```{r, percentage in sum, echo = FALSE}
# Q4.tbl.am.2 <- addmargins(Q4.tbl, margin = 1)
# pander(round(prop.table(Q4.tbl.am.2[3, ])*100, digits = 1))
```
-->

```{r, save, echo = FALSE}
# save.image("../R/quiz1102.rda")
```