---
title: "Quiz 160907"
author: "coop711"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# install.packages("pander", repos = "https://cran.rstudio.com")
# install.packages("xlsx", repos = "https://cran.rstudio.com")
library(xlsx)
library(pander)
library(knitr)
panderOptions('table.split.table', Inf)
panderOptions('table.alignment.rownames', 'left')
panderOptions('table.alignment.default', 'right')
options(width=180, digits = 2)
```

```{r, data, echo = FALSE, results = 'hide'}
quiz0907_test <- read.xlsx("../data/quiz0907_test.xlsx", 1, startRow = 2, endRow = 102, colIndex = c(3:7, 9:14), colClasses = c(rep("character", 11)), stringsAsFactors = FALSE)
str(quiz0907_test)
names(quiz0907_test) <- c("dept", "id", "name", "year", "e.mail", "cell.no", "Q1", "Q2", "Q3", "Q4", "group")
na.group <- is.na(quiz0907_test$group)
load("./red_and_black_160907_data.rda")
quiz0907_test$group[na.group] <- levels(class_roll0907$group[na.group])
quiz0907_test$dept <- factor(quiz0907_test$dept)
quiz0907_test$year <- factor(quiz0907_test$year)
quiz0907_test$group <- factor(quiz0907_test$group, levels = c("Red", "Black"))
quiz0907_test$Q1 <- factor(quiz0907_test$Q1, levels = c("가", "나", "다", "라", "무응답"), labels = c("1/10", "1/15", "1/20", "1/30", "무응답"))
quiz0907_test$Q2 <- factor(quiz0907_test$Q2, levels = c("가", "나", "다", "라"), labels = c("15만호", "20만호", "44만호", "130만호"))
quiz0907_test$Q3 <- factor(quiz0907_test$Q3, levels = c("가", "나", "다", "라", "마"), labels = c("경기", "평안", "전라", "경상", "충청"))
quiz0907_test$Q4 <- factor(quiz0907_test$Q4, levels = c("가", "나", "다", "라", "마", "바"))
quiz0907_test$Q4.2 <- quiz0907_test$Q4
levels(quiz0907_test$Q4.2[quiz0907_test$group == "Black"]) <- c("마", "라", "다", "나", "가", "바")
levels(quiz0907_test$Q4.2) <- c("A", "B", "C", "D", "E", "기타 또는 없음")
str(quiz0907_test)
```

```{r, randomization, echo = FALSE, results = 'hide'}
pander(summary(quiz0907_test))
```

### 퀴즈 응답 비교

#### 공법

##### 기본세율

```{r, National and Local tax, echo = FALSE}
Q1.tbl.am <- addmargins(table(quiz0907_test$group, quiz0907_test$Q1, exclude = NULL), margin = 1)
colnames(Q1.tbl.am)[6] <- "결석"
rownames(Q1.tbl.am)[4] <- "계"
pander(Q1.tbl.am[-3, ])
```

##### 기본세율(%)

```{r, National and Local tax in percentage, echo = FALSE}
pander(format(prop.table(Q1.tbl.am, margin = 1)[4, ]*100, nsmall = 1))
```

#### 1423년 조선시대 호구와 인구

##### 호구와 인구

```{r, tax law and cabinets, echo = FALSE}
Q2.tbl.am <- addmargins(table(quiz0907_test$group, quiz0907_test$Q2, exclude = NULL), margin = 1)
colnames(Q2.tbl.am)[5] <- "결석"
rownames(Q2.tbl.am)[4] <- "계"
pander(Q2.tbl.am[-3, ])
```

##### 호구와 인구(%)

```{r, tax law and cabinets in percentage, echo = FALSE}
pander(format(prop.table(Q2.tbl.am, margin = 1)[4,]*100, nsmall = 1), caption="공법도입과 대신들")
```

#### 지방관료와 품관촌민

##### 찬반이 반대인 곳(집계표)

```{r, tax law and laymen, echo = FALSE}
Q3.tbl.am <- addmargins(table(quiz0907_test$group, quiz0907_test$Q3, exclude = NULL), margin = 1)
colnames(Q3.tbl.am)[6] <- "결석"
rownames(Q3.tbl.am)[4] <- "계"
pander(Q3.tbl.am[-3, ])
```

##### 찬반이 반대인 곳(%)

```{r, tax law and laymen in percentage, echo = FALSE}
pander(format(prop.table(Q3.tbl.am, margin = 1)[4, ]*100, nsmall = 1), caption="품관촌민들의 찬반")
```

### 대선 후보 지지도

#### 질문지 답 문항 순서의 영향

##### 가나다 순으로 후보 이름을 늘어놓는지(Red), 가나다 역순으로 후보 이름을 늘어놓는지(Black)에 따라 응답이 달라질 것으로 기대. Red 와 Black의 응답이 다르게 나타나고 있는 점에 유의. 후보들은 최근 여론조사에서 꾸준히 5% 이상 지지율을 얻고 있는 사람들로 선정.

```{r, outs merge, echo = FALSE}
poll.tbl.e <- table(quiz0907_test$group, quiz0907_test$Q4.2, exclude = NULL)
colnames(poll.tbl.e)[7] <- "결석"
pander(poll.tbl.e[-3, ], caption = "대선후보지지도")
```

##### % 비교.  

```{r, outs merge in percentage, echo = FALSE}
merge.tbl <- table(quiz0907_test$group, quiz0907_test$Q4.2)
pander(format(prop.table(merge.tbl, margin = 1)*100, nsmall = 1), caption = "대선후보지지도")
```

```{r, save, echo = FALSE}
save.image("./quiz0907_test.rda")
```