---
title: "Quiz 170315"
author: "coop711"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# install.packages("pander", repos = "https://cran.rstudio.com")
# install.packages("xlsx", repos = "https://cran.rstudio.com")
library(xlsx)
library(pander)
library(knitr)
panderOptions('table.split.table', Inf)
panderOptions('table.alignment.rownames', 'left')
panderOptions('table.alignment.default', 'right')
options(width=180)
```

```{r, data, echo = FALSE, results = 'hide'}
quiz0313 <- read.xlsx("../data/quiz0313.xlsx", 1, startRow = 2, endRow = 163, colIndex = c(3:7, 9:15),
                      colClasses=c(rep("character", 12)), stringsAsFactors = FALSE)
str(quiz0313)
names(quiz0313) <- c("dept", "id", "name", "year", "e.mail", "cell.no", "Q1", "Q2", "Q3", "Q4", "group", "group.roll")
quiz0313$dept <- factor(quiz0313$dept)
quiz0313$year <- factor(quiz0313$year)
quiz0313$group <- factor(quiz0313$group, levels = c("Red", "Black"))
quiz0313$group.roll <- factor(quiz0313$group.roll, levels = c("Red", "Black"))
quiz0313$Q1 <- factor(quiz0313$Q1, levels = c("가", "나", "다", "라", "마"), labels = c("9:1", "8:2", "7:3", "6:4", "5:5"))
quiz0313$Q2 <- factor(quiz0313$Q2, levels = c("가", "나", "다", "라", "마"), labels = c("10%", "30%", "50%", "70%", "90%"))
quiz0313$Q3 <- factor(quiz0313$Q3, levels = c("가", "나", "다", "라", "마"), labels = c("7:3", "6:4", "5:5", "4:6", "3:7"))
```

### Group 확인

```{r, cross table, echo = FALSE, results = 'markup'}
tbl.q <- table("출석부" = quiz0313$group.roll, "퀴즈" = quiz0313$group, useNA = "ifany")
tbl.q.a <- addmargins(tbl.q)
# tbl.q.a
colnames(tbl.q.a)[3:4] <- c("결석", "계")
rownames(tbl.q.a)[3] <- c("계")
pander(tbl.q.a)
```

```{r, Q4 reassignment, echo = FALSE, results = 'hide'}
na.group <- is.na(quiz0313$group)
cbind(quiz0313$group[na.group], quiz0313$group.roll[na.group])
quiz0313$group[na.group] <- quiz0313$group.roll[na.group]
cbind(quiz0313$group[na.group], quiz0313$group.roll[na.group])
quiz0313$Q4 <- factor(quiz0313$Q4, levels = c("가", "나", "다", "라"))
quiz0313$Q4.2 <- quiz0313$Q4
levels(quiz0313$Q4.2[quiz0313$group == "Black"]) <- c("다", "나", "가", "라")
levels(quiz0313$Q4.2) <- c("구속 수사", "불구속 수사", "수사 불필요", "잘 모르겠다")
str(quiz0313)
```

### 퀴즈 응답 비교

#### 우리나라 국세와 지방세 배분비율

##### 국세와 지방세

```{r, National and Local tax, echo = FALSE}
Q1.tbl.am <- addmargins(table(quiz0313$group, quiz0313$Q1, exclude = NULL), margin = 1)
colnames(Q1.tbl.am)[6] <- "결석"
rownames(Q1.tbl.am)[3] <- "계"
pander(Q1.tbl.am[-3, ])
# pander(addmargins(table(quiz0313$group, quiz0313$Q1, exclude = NULL), margin=1))
```

##### 국세와 지방세(%)

```{r, National and Local tax in percentage, echo = FALSE}
pander(round(prop.table(Q1.tbl.am, margin = 1)[3, ]*100, digits = 2))
# pander(round(prop.table(addmargins(table(quiz0313$group, quiz0313$Q1, exclude = NULL), margin=1), margin=1)[4,]*100, digits=1))
```

#### 공법도입에 대한 대신들의 찬성율

##### 공법도입과 대신들(집계표)

```{r, tax law and cabinets, echo = FALSE}
Q2.tbl.am <- addmargins(table(quiz0313$group, quiz0313$Q2, exclude = NULL), margin = 1)
colnames(Q2.tbl.am)[6] <- "결석"
rownames(Q2.tbl.am)[3] <- "계"
pander(Q2.tbl.am[-3, ])
# pander(addmargins(table(quiz0313$group, quiz0313$Q2, exclude = NULL), margin=1))
```

##### 공법도입과 대신들(%)

```{r, tax law and cabinets in percentage, echo = FALSE}
pander(round(prop.table(Q2.tbl.am, margin = 1)[3, ]*100, digits = 2))
# pander(round(prop.table(addmargins(table(quiz0313$group, quiz0313$Q2, exclude = NULL), margin=1), margin=1)[4,]*100, digits=1), caption="공법도입과 대신들")
```

#### 공법도입과 품관촌민들의 찬반

##### 품관촌민들의 찬반(집계표)

```{r, tax law and laymen, echo = FALSE}
Q3.tbl.am <- addmargins(table(quiz0313$group, quiz0313$Q3, exclude = NULL), margin = 1)
colnames(Q3.tbl.am)[6] <- "결석"
rownames(Q3.tbl.am)[3] <- "계"
pander(Q3.tbl.am[-3, ])
# pander(addmargins(table(quiz0313$group, quiz0313$Q3, exclude = NULL), margin=1))
```

##### 품관촌민들의 찬반(%)

```{r, tax law and laymen in percentage, echo = FALSE}
pander(round(prop.table(Q3.tbl.am, margin = 1)[3, ]*100, digits = 2))
# pander(round(prop.table(addmargins(table(quiz0313$group, quiz0313$Q3, exclude = NULL), margin=1), margin=1)[4,]*100, digits=1), caption="품관촌민들의 찬반")
```

### 탄핵 인용과 전대통령 수사

#### 질문지 답 문항 순서의 영향

##### 강경한 조치 순으로 답 문항을 늘어놓는지(Red), 순한 조치 순으로 답 문항을 늘어놓는지(Black)에 따라 응답이 달라질 것으로 기대. Red 와 Black의 응답이 다르게 나타나고 있는 점에 유의!

```{r, investigation, echo = FALSE}
tbl.e <- table(quiz0313$group, quiz0313$Q4.2, exclude = NULL)
colnames(tbl.e)[5] <- "결석"
pander(tbl.e[-3, ], caption ="피의자 박근혜 수사 방식")
# pander(table(quiz0313$group, quiz0313$Q4.2, exclude = NULL), caption="야권통합논란")
```

##### % 비교.  

```{r, investigation in percentage, echo = FALSE}
tbl <- table(quiz0313$group, quiz0313$Q4.2)
pander(round(prop.table(tbl, margin = 1)*100, digits = 1))
```

```{r, save, echo = FALSE}
save.image("./quiz0313.RData")
```