---
title: "Quiz 161024"
author: "coop711"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# install.packages("pander", repos = "https://cran.rstudio.com")
# install.packages("xlsx", repos = "https://cran.rstudio.com")
library(xlsx)
library(pander)
library(knitr)
panderOptions('table.split.table', Inf)
panderOptions('table.alignment.rownames', 'left')
panderOptions('table.alignment.default', 'right')
options(width = 180)
```

```{r, data, echo = FALSE, results = 'hide'}
quiz1024 <- read.xlsx("../data/quiz1024.xlsx", 1, startRow = 2, endRow = 97, colIndex = c(3:7, 9:14), colClasses = c(rep("character", 11)), stringsAsFactors = FALSE)
str(quiz1024)
names(quiz1024) <- c("dept", "id", "name", "year", "e.mail", "cell.no", "Q1", "Q2", "Q3", "Q4", "group")
quiz1024$dept <- factor(quiz1024$dept)
quiz1024$year <- factor(quiz1024$year)
quiz1024$group <- factor(quiz1024$group, levels = c("Red", "Black"))
quiz1024$Q1 <- factor(quiz1024$Q1, levels = c("가", "나", "다", "라"), labels = c("대공황, 대침체", "대침체, 대공황", "대번영, 대공황", "대공황, 대번영"))
quiz1024$Q2 <- factor(quiz1024$Q2, levels = c("가", "나", "다", "라"), labels = c("소득불평등, 양의상관", "소득, 양의 상관", "소득불평등, 인과관계", "소득, 인과관계"))
quiz1024$Q3 <- factor(quiz1024$Q3, levels = c("가", "나", "다", "라"), labels = c("7.0%", "35%", "70%", "94%"))
quiz1024$Q4 <- factor(quiz1024$Q4, levels = c("A", "B"))
# quiz1024$Q4.2 <- quiz1024$Q4
# quiz1024$Q4.2[quiz1024$group == "Black"] <- factor(quiz1024$Q4.2[quiz1024$group == "Black"], levels = c("A", "B"), labels = c("100%확률로 잃기", "90%확률로 잃기"))
# quiz1024$Q4.2[quiz1024$group == "Red"] <- factor(quiz1024$Q4.2[quiz1024$group == "Red"], levels = c("A", "B"), labels = c("100%확률로 따기", "90%확률로 따기"))
str(quiz1024)
```

```{r, randomization, echo = FALSE, results = 'hide'}
pander(summary(quiz1024))
```

### 퀴즈 응답 비교

#### 소득 상위1%의 몫과 시대적 사건들

##### 대공황. 대번영, 대침체

```{r, times, echo = FALSE}
Q1.tbl.am <- addmargins(table(quiz1024$group, quiz1024$Q1, exclude = NULL), margin = 1)
colnames(Q1.tbl.am)[5] <- "결석"
rownames(Q1.tbl.am)[4] <- "계"
pander(Q1.tbl.am[-3, ])
```

##### 대공황. 대번영, 대침체(%)

```{r,times in percentage, echo = FALSE}
pander(round(prop.table(Q1.tbl.am, margin = 1)[4, ]*100, digits = 1))
```

#### Wilkinson

##### 소득불평등과 건강 및 사회문제 지표

```{r, inequality, echo = FALSE}
Q2.tbl.am <- addmargins(table(quiz1024$group, quiz1024$Q2, exclude = NULL), margin = 1)
colnames(Q2.tbl.am)[5] <- "결석"
rownames(Q2.tbl.am)[4] <- "계"
pander(Q2.tbl.am[-3, ])
```

##### 소득불평등과 건강 및 사회문제 지표 (%)

```{r, inequality in percentage, echo = FALSE}
pander(round(prop.table(Q2.tbl.am, margin = 1)[4,]*100, digits=1))
```

#### 1944년 미국의 최고소득세율

##### 최고소득세율 94%

```{r, MTR, echo = FALSE}
Q3.tbl.am <- addmargins(table(quiz1024$group, quiz1024$Q3, exclude = NULL), margin = 1)
colnames(Q3.tbl.am)[5] <- "결석"
rownames(Q3.tbl.am)[4] <- "계"
pander(Q3.tbl.am[-3, ])
```

##### 최고소득세율 94% (%)

```{r, MTRE in percentage, echo = FALSE}
pander(round(prop.table(Q3.tbl.am, margin = 1)[4,]*100, digits = 1))
```

### Prospect Theory

#### 이득과 손실

##### 이득은 완전히 하고, 손실은 피하고자 하는 경향 확인. Red는 이득을 완전히 확보하려는 게임(A)에, Black은 손실을 확률적으로 피하려는 게임(B)을 많이 선택.

```{r, prospect theory, echo = FALSE}
Q4.tbl.e <- table(quiz1024$group, quiz1024$Q4, exclude = NULL)
Q4.tbl.am <- addmargins(Q4.tbl.e, margin = 1)
colnames(Q4.tbl.am)[3] <- "결석"
rownames(Q4.tbl.am)[4] <- "계"
pander(Q4.tbl.am[-3, ])
# kable(table(quiz1024$group, quiz1024$Q4, exclude = NULL), caption = "손실회피심리")
```

##### % 비교.  

```{r, prospect theory  in percentage, echo = FALSE}
Q4.tbl <- table(quiz1024$group, quiz1024$Q4)
pander(round(prop.table(Q4.tbl, margin = 1)*100, digits = 1))
# merge.tbl <- table(quiz1024$group, quiz1024$Q4)
# kable(round(prop.table(merge.tbl, margin = 1)*100, digits = 1))
```

```{r, save, echo = FALSE}
#save.image("../R/quiz1024.rda")
```