---
title: "Quiz 170510"
author: "coop711"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# install.packages("pander", repos = "https://cran.rstudio.com")
# install.packages("xlsx", repos = "https://cran.rstudio.com")
library(xlsx)
library(pander)
library(knitr)
panderOptions('table.split.table', Inf)
panderOptions('table.alignment.rownames', 'left')
panderOptions('table.alignment.default', 'right')
options(width = 180)
```

```{r, data, echo = FALSE, results = 'hide'}
quiz0510 <- read.xlsx("../data/quiz170510.xlsx", 1, startRow = 2, endRow = 161, colIndex = c(3:7, 9:14), colClasses = c(rep("character", 11)), stringsAsFactors = FALSE)
str(quiz0510)
names(quiz0510) <- c("dept", "id", "name", "year", "e.mail", "cell.no", "Q1", "Q2", "Q3", "Q4", "group")
quiz0510$dept <- factor(quiz0510$dept)
quiz0510$year <- factor(quiz0510$year)
quiz0510$group <- factor(quiz0510$group, levels = c("Red", "Black"))
quiz0510$Q1
# strsplit(quiz0510$Q1, ",")
BFI.strsplit <- strsplit(quiz0510$Q1, ",")
# str(BFI.strsplit)
# BFI.first <- mapply(function(x) sapply(x, substr, 1, 1), BFI.strsplit)
# BFI.str.collapse <- mapply(function(x) paste(x, sep ="", collapse = ""), BFI.strsplit)
# BFI.replies <- mapply(function(x) substring(x, first = c(1, 4, 7, 10, 13), last = c(1, 4, 7, 10, 13)), BFI.str.collapse)
BFI.ans <- strsplit("개방성,성실성,외향성,친화성,신경성", split = ",")
BFI.count <- mapply(function(x) ifelse(x == unlist(BFI.ans), 1, 0), BFI.strsplit)
# BFI.count <- mapply(function(x) ifelse(x == unlist(BFI.ans), 1, 0), BFI.first)
# BFI.count <- mapply(function(x) ifelse(x == unlist(BFI.ans), 1, 0), data.frame(BFI.replies))
BFI.score <- apply(BFI.count, 2, sum)
# quiz0510$Q2[49]
MI.strsplit <- strsplit(quiz0510$Q2, ",")
# str(MI.strsplit)
# MI.first <- mapply(function(x) sapply(x, substr, 1, 1), MI.strsplit)
# MI.str.collapse <- mapply(function(x) paste(x, sep ="", collapse = ""), MI.strsplit)
# MI.replies <- mapply(function(x) substring(x, first = c(1, 4, 7, 10, 13), last = c(1, 4, 7, 10, 13)), MI.str.collapse)
MI.strsplit[[49]]
MI.ans <- strsplit("신체운동,음악,공간,자기성찰,자연친화,논리수학,언어,인간친화", split = ",")
MI.count <- mapply(function(x) ifelse(x == unlist(MI.ans), 1, 0), MI.strsplit)
# MI.count <- mapply(function(x) ifelse(x == unlist(MI.ans), 1, 0), data.frame(MI.replies))
MI.score <- apply(MI.count, 2, sum)
quiz0510[c("Q3", "Q4", "group")]
quiz0510$Q3.2 <- quiz0510$Q3
Black <- quiz0510$group == "Black"
Red <- quiz0510$group == "Red"
quiz0510$Q3.2[Black] <- ifelse(quiz0510$Q3[Black] == "Beer,17", "Right", "Wrong")
quiz0510$Q3.2[Red] <- ifelse(quiz0510$Q3[Red] == "A,3", "Right", "Wrong")
# quiz0510$Q3.2[Black] <- ifelse(quiz0510$Q3[Black] == "Beer,17", "Right", "Wrong")
# quiz0510$Q3.2[Red] <- ifelse(quiz0510$Q3[Red] == "A,3", "Right", "Wrong")
# quiz0510$Q3.2[quiz0510$group == "Black" & quiz0510$Q3 == "Beer,17"] <- "Right"
# quiz0510$Q3.2[quiz0510$group == "Black" & quiz0510$Q3 != "Beer,17"] <- "Wrong"
# quiz0510$Q3.2[quiz0510$group == "Red" & quiz0510$Q3 == "A,3"] <- "Right"
# quiz0510$Q3.2[quiz0510$group == "Red" & quiz0510$Q3 != "A,3"] <- "Wrong"
quiz0510$Q3.2
quiz0510$Q4.2 <- quiz0510$Q4
quiz0510$Q4.2[Black] <- ifelse(quiz0510$Q4[Black] == "A,3", "Right", "Wrong")
quiz0510$Q4.2[Red] <- ifelse(quiz0510$Q4[Red] == "Beer,17", "Right", "Wrong")
# quiz0510$Q4.2[Black] <- ifelse(quiz0510$Q4[Black] == "A,3", "Right", "Wrong")
# quiz0510$Q4.2[Red] <- ifelse(quiz0510$Q4[Red] == "Beer,17", "Right", "Wrong")
# quiz0510$Q4.2[quiz0510$group == "Black" & quiz0510$Q4 == "A,3"] <- "Right"
# quiz0510$Q4.2[quiz0510$group == "Black" & quiz0510$Q4 != "A,3"] <- "Wrong"
# quiz0510$Q4.2[quiz0510$group == "Red" & quiz0510$Q4 == "Beer,17"] <- "Right"
# quiz0510$Q4.2[quiz0510$group == "Red" & quiz0510$Q4 != "Beer,17"] <- "Wrong"
quiz0510[c("Q3", "Q3.2", "Q4", "Q4.2", "group")]
str(quiz0510)
```

```{r, randomization, echo = FALSE, results = 'hide'}
pander(summary(quiz0510))
```

### 퀴즈 응답

#### BFI 줄 긋기

##### 몇 개나 맞추나?

```{r, BFI, echo = FALSE}
BFI.tbl <- table(quiz0510$group, BFI.score, useNA = "ifany")
BFI.tbl.a <- addmargins(BFI.tbl)
rownames(BFI.tbl.a)[3] <- "계" 
colnames(BFI.tbl.a)[5:6] <- c("결석", "계")
pander(BFI.tbl.a)
```

##### 몇 개나 맞추나? (%)

```{r, BFi percentage, echo = FALSE}
BFI.tbl.p <- round(prop.table(table(BFI.score)) * 100, digits = 2)
BFI.tbl.a.m <- addmargins(BFI.tbl.p, margin = 1)
names(BFI.tbl.a.m)[5] <- "계"
pander(BFI.tbl.a.m, caption = "Big Five Inventory")
```

#### 다중 지능

##### 몇 개나 맞추나?

```{r, MI, echo = FALSE}
MI.score.tbl <- table(quiz0510$group, "맞춘 갯수" = MI.score, useNA = "ifany")
MI.score.tbl.a <- addmargins(MI.score.tbl)
rownames(MI.score.tbl.a)[3] <- "계"
colnames(MI.score.tbl.a)[7:8] <- c("결석", "계")
pander(MI.score.tbl.a, caption = "Multitple Intelligence")
pander(chisq.test(cbind(rowSums(MI.score.tbl[, 1:5]), MI.score.tbl[, 6:7])))
```

##### 몇 개나 맞추나? (%)

```{r, MI percentage, echo = FALSE}
MI.tbl.p <- round(prop.table(table(MI.score))*100, digits = 2)
MI.tbl.a.m <- addmargins(MI.tbl.p, margin = 1)
names(MI.tbl.a.m)[7] <- "계"
pander(MI.tbl.a.m, caption = "Multiple Intelligence")
```

### Wason Selection


#### 추상적 표현과 구체적 표현?

같은 내용의 문제를 추상적으로 물어볼 때와 구체적으로 사례를 들어서 물어볼 때의 정답률에 큰 차이가 있음에 유의. Red 집단에게는 추상적 질문을 먼저 던지고, 구체적 사례를 든 질문을 나중에 던졌으며 Black 집단에게는 구체적 사례를 든 질문을 먼저 던지고, 추상적 질문을 나중에 던졌다. 동일한 질문에 대해서 순서에 따른 차이는 거의 없지만 추상적이냐 구체적이냐에 따른 차이는 매우 높게 관찰된다. 추상적인 질문에 쩔쩔매는 게 정상이다.

##### Red에 추상적 문제 먼저 질문 

```{r, Wason Selection 1 in Red, echo = FALSE}
tbl.q3.a <- addmargins(table(quiz0510$group, quiz0510$Q3.2, useNA = "ifany"), margin = 1)
rownames(tbl.q3.a) <- c("Red(추상적 질문 먼저)", "Black(구체적 질문 먼저)", "계") 
colnames(tbl.q3.a) <- c("정답", "오답", "계")
# tbl.q3.a <- addmargins(tbl.q3, margin = 1)
kable(tbl.q3.a)
```

##### % 비교  

```{r, Wason Selection 1 in Red in percentage, echo = FALSE}
percentage.tbl.q3.a <- addmargins(round(prop.table(tbl.q3.a[, -3], margin = 1)*100, digits = 1))[1:2, ]
colnames(percentage.tbl.q3.a) <- c("정답", "오답", "계")
kable(percentage.tbl.q3.a)
```

##### Black에 구체적 문제 먼저 질문 

```{r, Wason Selection 1 in Black, echo = FALSE}
tbl.q4.a <- addmargins(table(quiz0510$group, quiz0510$Q4.2, useNA = "ifany"), margin = 1)
rownames(tbl.q4.a) <- c("Red(구체적 질문 먼저)", "Black(추상적 질문 먼저)", "계")
colnames(tbl.q4.a) <- c("정답", "오답", "계")
kable(tbl.q4.a)
```

##### % 비교.  

```{r, Wason Selection 1 in Black in percentage, echo = FALSE}
percentage.tbl.q4.a <- addmargins(round(prop.table(tbl.q4.a[, -3], margin = 1)*100, digits = 1))[1:2, ]
colnames(percentage.tbl.q4.a) <- c("정답", "오답", "계")
kable(percentage.tbl.q4.a)
```

#### 합산

##### 집계표

```{r, Wason Selection, echo = FALSE}
wason_1 <- tbl.q3.a[1, ] + tbl.q4.a[2, ]
wason_2 <- tbl.q3.a[2, ] + tbl.q4.a[1, ]
wason.tbl <- as.table(rbind(wason_1, wason_2))
rownames(wason.tbl) <- c("Wason 1(추상적 질문)", "Wason 2(구체적 질문)")
kable(wason.tbl, caption = "Wason Selection")
```

##### % 비교

```{r, Wason Selection in percentage, echo = FALSE}
wason.tbl.p.a <- addmargins(round(prop.table(wason.tbl[, -3], margin = 1)*100, digits = 1))[1:2, ]
colnames(wason.tbl.p.a) <- c("정답", "오답","계")
kable(wason.tbl.p.a, caption = "Wason Selection")
```

```{r, save, echo = FALSE}
#save.image("../R/quiz0510.rda")
```