---
title: "Quiz 161010"
author: "coop711"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# install.packages("pander", repos = "https://cran.rstudio.com")
# install.packages("xlsx", repos = "https://cran.rstudio.com")
library(xlsx)
library(pander)
library(knitr)
panderOptions('table.split.table', Inf)
panderOptions('table.alignment.rownames', 'left')
panderOptions('table.alignment.default', 'right')
options(width=180)
```

```{r, data, echo = FALSE, results = 'hide'}
quiz1010 <- read.xlsx("../data/quiz1010.xlsx", 1, startRow = 2, endRow = 102, colIndex = c(3:7, 9:14), colClasses = c(rep("character", 11)), stringsAsFactors=FALSE)
str(quiz1010)
names(quiz1010) <- c("dept", "id", "name", "year", "e.mail", "cell.no", "Q1", "Q2", "Q3", "Q4", "group")
quiz1010$dept <- factor(quiz1010$dept)
quiz1010$year <- factor(quiz1010$year)
quiz1010$group <- factor(quiz1010$group, levels = c("Red", "Black"))
quiz1010$Q1 <- factor(quiz1010$Q1, levels = c("가", "나", "다", "라", "마"), labels = c("대한민국", "일본", "독일", "미국", "캐나다"))
quiz1010$Q2 <- factor(quiz1010$Q2, levels = c("가", "나", "다", "라"), labels = c("일본 5.7%", "OECD 평균 11.9%", "룩셈부르크 15.1%", "대한민국 28.2%"))
quiz1010$Q3 <- factor(quiz1010$Q3, levels = c("가", "나", "다", "라", "마", "무응답"), labels = c("OECD 평균 21.9%", "터키 12.8%", "칠레 10.2%", "한국 10.2%", "멕시코 7.4%", "무응답"))
# Q4.na <- is.na(quiz1010$Q4)
# quiz1010$Q4 <- ifelse(is.na(quiz1010$Q4), "결석", quiz1010$Q4)
quiz1010$Q4.2 <- quiz1010$Q4
Red <- quiz1010$group == "Red"
Black <- quiz1010$group == "Black"
quiz1010$Q4.2[Red & quiz1010$Q4.2 == "No Check"] <- "있음"
quiz1010$Q4.2[Red & quiz1010$Q4.2 == "Check"] <- "없음"
quiz1010$Q4.2[Black & quiz1010$Q4.2 == "No Check"] <- "없음"
quiz1010$Q4.2[Black & quiz1010$Q4.2 == "Check"] <- "있음"
# quiz1010$Q4.2[quiz1010$Q4.2 == "NA"] <- NA
quiz1010$Q4.2 <- factor(quiz1010$Q4.2, level = c("있음", "없음"))
quiz1010$Q4
```

```{r, randomization, echo = FALSE, results = 'hide'}
pander(summary(quiz1010))
```

### 퀴즈 응답 비교

#### OECD 2014년 3분기 실업률 비교

##### 가장 낮은 나라

```{r, PDI, echo = FALSE}
Q1.tbl.am <- addmargins(table(quiz1010$group, quiz1010$Q1, exclude = NULL), margin = 1)
colnames(Q1.tbl.am)[6] <- "결석"
rownames(Q1.tbl.am)[4] <- "계"
pander(Q1.tbl.am[-3, ], caption = "실업율 가장 낮은 나라")
# pander(addmargins(table(quiz1010$group, quiz1010$Q1, exclude = NULL), margin=1))
```

##### 가장 낮은 나라 (%)

```{r, PDI in percentage, echo = FALSE}
pander(round(prop.table(Q1.tbl.am, margin = 1)[4, ]*100, digits = 1))
# pander(round(prop.table(addmargins(table(quiz1010$group, quiz1010$Q1, exclude = NULL), margin=1), margin=1)[4,]*100, digits=1))
```

#### 자영업자의 비율

##### 제대로 파악한 것은?

```{r, self-employed, echo = FALSE}
Q2.tbl.am <- addmargins(table(quiz1010$group, quiz1010$Q2, exclude = NULL), margin = 1)
colnames(Q2.tbl.am)[5] <- "결석"
rownames(Q2.tbl.am)[4] <- "계"
pander(Q2.tbl.am[-3, ], "자영업자의 비율")
# pander(addmargins(table(quiz1010$group, quiz1010$Q2, exclude = NULL), margin=1))
```

##### 자영업자의 비율 (%)

```{r, self-employed in percentage, echo = FALSE}
pander(round(prop.table(Q2.tbl.am, margin = 1)[4,]*100, digits=1), caption = "자영업자의 비율")
# pander(round(prop.table(addmargins(table(quiz1010$group, quiz1010$Q2, exclude = NULL), margin=1), margin=1)[4,]*100, digits=1), caption="자영업자의 어려움")
```

#### 우리나라 GDP 대비 공공사회지출 비중은 터키 아래

##### OECD GDP 대비 공공사회지출 비중

```{r, public expenditure, echo = FALSE}
Q3.tbl.am <- addmargins(table(quiz1010$group, quiz1010$Q3, exclude = NULL), margin = 1)
colnames(Q3.tbl.am)[7] <- "결석"
rownames(Q3.tbl.am)[4] <- "계"
pander(Q3.tbl.am[-3, ], caption = "공공사회지출 비중")
# pander(addmargins(table(quiz1010$group, quiz1010$Q3, exclude = NULL), margin=1))
```

##### OECD GDP 대비 공공사회지출 비중 (%)

```{r, public expenditure in percentage, echo = FALSE}
pander(round(prop.table(Q3.tbl.am, margin = 1)[4,]*100, digits = 1), caption = "공공사회지출 비중")
# pander(round(prop.table(addmargins(table(quiz1010$group, quiz1010$Q3, exclude = NULL), margin = 1), margin = 1)[4,]*100, digits = 1), caption = "공공사회지출 비중")
```

### 디폴트 효과

#### 표시하지 않으면 ... 으로 간주합니다의 효과

##### 표시하지 않으면 대선 투표의사가 있는 것으로 간주하는 경우(Red)와 표시하면 대선 투표의사가 있는 것으로 간주하는 경우(Black), 표시하지 않으면 투표의사가 있다고 보는 질문지에 투표의사 비율이 더 높게 나온다는 것에 유의. 어디다 디폴트를 두느냐에 따라 조사결과가 달라짐.

```{r, vote attitude, echo = FALSE}
Q4.tbl.e <- table(quiz1010$group, quiz1010$Q4.2, exclude = NULL)
Q4.tbl.am <- addmargins(Q4.tbl.e, margin = 1)
colnames(Q4.tbl.am)[3] <- "결석"
rownames(Q4.tbl.am)[4] <- "계"
pander(Q4.tbl.am[-3, ], caption = "대선 투표의사")
```

##### % 비교.  

```{r, vote attitude in percentage, echo = FALSE}
Q4.tbl <- table(quiz1010$group, quiz1010$Q4.2)
pander(round(prop.table(Q4.tbl, margin = 1)*100, digits = 1))
```

#### 합산

```{r, percentage in sum, echo = FALSE}
Q4.tbl <- table(quiz1010$group, quiz1010$Q4.2)
Q4.tbl.am.2 <- addmargins(Q4.tbl, margin = 1)
pander(round(prop.table(Q4.tbl.am.2[3, ])*100, digits = 1))
```

```{r, save, echo = FALSE}
save.image("../R/quiz1010.rda")
```
