---
title: "Quiz 161031"
author: "coop711"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# install.packages("pander", repos = "https://cran.rstudio.com")
# install.packages("xlsx", repos = "https://cran.rstudio.com")
library(xlsx)
library(pander)
library(knitr)
panderOptions('table.split.table', Inf)
panderOptions('table.alignment.rownames', 'left')
panderOptions('table.alignment.default', 'right')
options(width = 180)
```

```{r, data, echo = FALSE, results = 'hide'}
quiz1031 <- read.xlsx("../data/quiz1031.xlsx", 1, startRow = 2, endRow = 97, colIndex = c(3:7, 9:14), colClasses = c(rep("character", 11)), stringsAsFactors = FALSE)
str(quiz1031)
names(quiz1031) <- c("dept", "id", "name", "year", "e.mail", "cell.no", "Q1", "Q2", "Q3", "Q4", "group")
quiz1031$dept <- factor(quiz1031$dept)
quiz1031$year <- factor(quiz1031$year)
quiz1031$group <- factor(quiz1031$group, levels = c("Red", "Black"))
quiz1031$Q1 <- factor(quiz1031$Q1, levels = c("가", "나", "다", "라"), labels = c("높을 때 높았다", "높이면 높아진다", "소득이 많았다", "소득이 많아진다"))
quiz1031$Q2 <- factor(quiz1031$Q2, levels = c("가", "나", "다", "라"), labels = c("황금기 함께 상승", "신자유주의시기 함께 상승", "신자유주의 시기 생산성 상승", "신자유주의 시기 임금 상승"))
quiz1031$Q3 <- factor(quiz1031$Q3, levels = c("가", "나", "다", "라", "조퇴"), labels = c("임금 상승 미흡", "급속한 고임금 증가율", "임금 격차 심화", "중산층 회복세", "조퇴"))
quiz1031$Q4.2 <- quiz1031$Q4
quiz1031$Q4.2[quiz1031$group == "Black" & quiz1031$Q4.2 == "가"] <- "아니다"
quiz1031$Q4.2[quiz1031$group == "Black" & quiz1031$Q4.2 == "나"] <- "하야"
quiz1031$Q4.2[quiz1031$group == "Black" & quiz1031$Q4.2 == "다"] <- "탄핵"
quiz1031$Q4.2[quiz1031$group == "Black" & quiz1031$Q4.2 == "라"] <- "모르겠다"
quiz1031$Q4.2[quiz1031$group == "Black" & quiz1031$Q4.2 == "조퇴"] <- "조퇴"
quiz1031$Q4.2[quiz1031$group == "Red" & quiz1031$Q4.2 == "가"] <- "탄핵"
quiz1031$Q4.2[quiz1031$group == "Red" & quiz1031$Q4.2 == "나"] <- "하야"
quiz1031$Q4.2[quiz1031$group == "Red" & quiz1031$Q4.2 == "다"] <- "아니다"
quiz1031$Q4.2[quiz1031$group == "Red" & quiz1031$Q4.2 == "라"] <- "모르겠다"
quiz1031$Q4.2[quiz1031$group == "Red" & quiz1031$Q4.2 == "조퇴"] <- "조퇴"
quiz1031$Q4.2 <- factor(quiz1031$Q4.2, levels = c("탄핵", "하야", "아니다", "모르겠다", "조퇴"))
str(quiz1031)
```

```{r, randomization, echo = FALSE, results = 'hide'}
pander(summary(quiz1031))
```

### 퀴즈 응답 비교

#### 최고한계세율과 소득집단별 소득증가

##### 황금기와 침체기

```{r, book of change, echo = FALSE}
Q1.tbl.am <- addmargins(table(quiz1031$group, quiz1031$Q1, exclude = NULL), margin = 1)
colnames(Q1.tbl.am)[5] <- "결석"
rownames(Q1.tbl.am)[4] <- "계"
pander(Q1.tbl.am[-3, ])
```

##### 황금기와 침체기(%)

```{r, book of change in percentage, echo = FALSE}
pander(round(prop.table(Q1.tbl.am, margin = 1)[4, ]*100, digits = 1))
```

#### 생산성과 임금

##### 황금기와 신자유주의 시기

```{r, opposite, echo = FALSE}
Q2.tbl.am <- addmargins(table(quiz1031$group, quiz1031$Q2, exclude = NULL), margin = 1)
colnames(Q2.tbl.am)[5] <- "결석"
rownames(Q2.tbl.am)[4] <- "계"
pander(Q2.tbl.am[-3, ])
```

##### 황금기와 신자유주의 시기 (%)

```{r, opposite in percentage, echo = FALSE}
pander(round(prop.table(Q2.tbl.am, margin = 1)[4,]*100, digits=1))
```

#### 생산성과 평균 및 중위 임금

##### 소득격차

```{r, MTR, echo = FALSE}
Q3.tbl.am <- addmargins(table(quiz1031$group, quiz1031$Q3, exclude = NULL), margin = 1)
colnames(Q3.tbl.am)[6] <- "결석"
rownames(Q3.tbl.am)[4] <- "계"
pander(Q3.tbl.am[-3, ])
```

##### 소득격차 (%)

```{r, MTRE in percentage, echo = FALSE}
pander(round(prop.table(Q3.tbl.am, margin = 1)[4,]*100, digits = 1))
```

### 국정농단

#### 탄핵, 하야?

##### 

```{r, Soonsil, echo = FALSE}
Q4.tbl.e <- table(quiz1031$group, quiz1031$Q4.2, exclude = NULL)
Q4.tbl.am <- addmargins(Q4.tbl.e, margin = 1)
colnames(Q4.tbl.am)[6] <- "결석"
rownames(Q4.tbl.am)[4] <- "계"
pander(Q4.tbl.am[-3, ])
```

##### % 비교.  

```{r, Soonsil in percentage, echo = FALSE}
Q4.tbl <- table(quiz1031$group, quiz1031$Q4.2)[, 1:4]
pander(round(prop.table(Q4.tbl, margin = 1)*100, digits = 1))
```

#### 합산(%)

```{r, percentage in sum, echo = FALSE}
Q4.tbl.am.2 <- addmargins(Q4.tbl, margin = 1)
pander(round(prop.table(Q4.tbl.am.2[3, ])*100, digits = 1))
```

```{r, save, echo = FALSE}
#save.image("../R/quiz1031.rda")
```