---
title: "Quiz 170306"
author: "coop711"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# install.packages("pander", repos = "https://cran.rstudio.com")
# install.packages("xlsx", repos = "https://cran.rstudio.com")
library(xlsx)
library(pander)
library(knitr)
panderOptions('table.split.table', Inf)
options(width=180)
```

```{r, data}
quiz0306 <- read.xlsx("../data/quiz0306.xlsx", 1, startRow = 2, endRow = 164, colIndex = c(3:7, 9:15), colClasses=c(rep("character", 11)), stringsAsFactors=FALSE)
str(quiz0306)
names(quiz0306) <- c("dept", "id", "name", "year", "e.mail", "cell.no", "Q1", "Q2", "Q3", "Q4", "group")
quiz0306$dept <- factor(quiz0306$dept)
quiz0306$year <- factor(quiz0306$year)
quiz0306$group <- factor(quiz0306$group, levels = c("Red", "Black"))
quiz0306$Q1 <- factor(quiz0306$Q1, levels = c("가", "나", "다", "라", "마"), labels = c("공자", "맹자", "관자", "노자", "장자"))
quiz0306$Q2 <- factor(quiz0306$Q2, levels = c("가", "나", "다", "라", "마"), labels = c("절대 중요 않음", "거의 중요 않음", "보통", "상당히 중요", "절대 중요"))
quiz0306$Q3 <- factor(quiz0306$Q3, levels = c("가", "나", "다", "라"), labels = c("2012", "2016", "2020", "2030"))
quiz0306$Q4 <- factor(quiz0306$Q4, levels = c("가", "나", "다"), labels = c("찬성 입장", "반대 입장", "모름/무응답"))
quiz0306$Q4.2 <- quiz0306$Q4
levels(quiz0306$Q4.2)
levels(quiz0306$Q4.2) <- c("찬성", "반대", "모름/무응답")
str(quiz0306)
```

```{r, randomization}
pander(summary(quiz0306))
```

```{r, id}
pander(table(quiz0306$group, quiz0306$Q1, exclude = NULL), caption="춘추시대 국가통계관리")
pander(addmargins(table(quiz0306$group, quiz0306$Q1, exclude = NULL), margin=1), caption="춘추시대 국가통계관리")
pander(round(prop.table(addmargins(table(quiz0306$group, quiz0306$Q1, exclude = NULL), margin=1), margin=1)[4,]*100, digits=1), caption="춘추시대 국가통계관리")
pander(table(quiz0306$group, quiz0306$Q2, exclude = NULL), caption="통계의 역할")
pander(addmargins(table(quiz0306$group, quiz0306$Q2, exclude = NULL), margin=1), caption="통계의 역할")
pander(round(prop.table(addmargins(table(quiz0306$group, quiz0306$Q2, exclude = NULL), margin=1), margin=1)[4,]*100, digits=1), caption="통계의 역할")
pander(table(quiz0306$group, quiz0306$Q3, exclude = NULL), caption="생산가능인구 감소")
pander(addmargins(table(quiz0306$group, quiz0306$Q3, exclude = NULL), margin=1), caption="생산가능인구 감소")
pander(round(prop.table(addmargins(table(quiz0306$group, quiz0306$Q3, exclude = NULL), margin=1), margin=1)[4,]*100, digits=1), caption="생산가능인구 감소")
pander(table(quiz0306$group, quiz0306$Q4, exclude = NULL), caption="테러방지법")
pander(table(quiz0306$group, quiz0306$Q4.2, exclude = NULL), caption="테러방지법")
thaad.tbl <- table(quiz0306$group, quiz0306$Q4)
thaad.tbl.2 <- table(quiz0306$group, quiz0306$Q4.2)
pander(round(prop.table(thaad.tbl, margin = 1)*100, digits = 1), caption="테러방지법(단위, %)")
pander(round(prop.table(thaad.tbl.2, margin = 1)*100, digits = 1), caption = "테러방지법(단위, %)")
```

```{r, save}
save.image("../R/quiz0306.RData")
```