---
title: "Quiz 170412"
author: "coop711"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# install.packages("pander", repos = "https://cran.rstudio.com")
# install.packages("xlsx", repos = "https://cran.rstudio.com")
library(xlsx)
library(pander)
library(knitr)
panderOptions('table.split.table', Inf)
panderOptions('table.alignment.rownames', 'left')
panderOptions('table.alignment.default', 'right')
options(width=180)
```

```{r, data, echo = FALSE, results = 'hide'}
quiz0412 <- read.xlsx("../data/quiz0412.xlsx", 1, startRow = 2, endRow = 161, colIndex = c(3:7, 9:14), colClasses = c(rep("character", 11)), stringsAsFactors=FALSE)
str(quiz0412)
names(quiz0412) <- c("dept", "id", "name", "year", "e.mail", "cell.no", "Q1", "Q2", "Q3", "Q4", "group")
quiz0412$dept <- factor(quiz0412$dept)
quiz0412$year <- factor(quiz0412$year)
quiz0412$group <- factor(quiz0412$group, levels = c("Red", "Black"))
quiz0412$Q1 <- factor(quiz0412$Q1, levels = c("가", "나", "다", "라", "마"), labels = c("10%", "25%", "33%", "45%", "50%"))
quiz0412$Q2 <- factor(quiz0412$Q2, levels = c("가", "나", "다", "라", "마"), labels = c("10%", "25%", "33%", "45%", "50%"))
quiz0412$Q3 <- factor(quiz0412$Q3, levels = c("가", "나", "다", "라", "마"), labels = c("미국", "터키", "칠레", "대한민국", "멕시코"))
quiz0412$Q4.2 <- quiz0412$Q4
Red <- quiz0412$group == "Red"
Black <- quiz0412$group == "Black"
quiz0412$Q4.2[Red & quiz0412$Q4.2 == "가"] <- "내가 남보다"
quiz0412$Q4.2[Red & quiz0412$Q4.2 == "나"] <- "남이 나보다"
quiz0412$Q4.2[Black & quiz0412$Q4.2 == "가"] <- "남이 나보다"
quiz0412$Q4.2[Black & quiz0412$Q4.2 == "나"] <- "내가 남보다"
quiz0412$Q4.2[quiz0412$Q4.2 == "NA"] <- NA
quiz0412$Q4.2 <- factor(quiz0412$Q4.2, level = c("내가 남보다", "남이 나보다"))
quiz0412$Q4
```

```{r, randomization, echo = FALSE, results = 'hide'}
pander(summary(quiz0412))
```

### 퀴즈 응답 비교{#퀴즈}

#### 소득 상위 10%의 소득점유율

##### 나의 판단

```{r, income concentration, echo = FALSE}
tbl.q3 <- table(quiz0412$group, quiz0412$Q1, exclude = NULL)
Q1.tbl.am <- addmargins(tbl.q3, margin = 1)
colnames(Q1.tbl.am)[6] <- "결석"
rownames(Q1.tbl.am)[3] <- "계"
pander(Q1.tbl.am)
pander(chisq.test(tbl.q3[-3, ]))

```

##### 나의 판단 (%)

```{r, income concentration in percentage, echo = FALSE}
pander(round(prop.table(Q1.tbl.am, margin = 1)[3, ]*100, digits = 1))
```

#### 소득 상위 10%의 소득점유율

##### 적정 수준

```{r, your judgement, echo = FALSE}
tbl.q2 <- table(quiz0412$group, quiz0412$Q2, exclude = NULL)
Q2.tbl.am <- addmargins(tbl.q2, margin = 1)
colnames(Q2.tbl.am)[6] <- "결석"
rownames(Q2.tbl.am)[3] <- "계"
pander(Q2.tbl.am)
pander(chisq.test(tbl.q2[-3, ]))
```

##### 적정 수준 (%)

```{r, your judgement in percentage, echo = FALSE}
pander(round(prop.table(Q2.tbl.am, margin = 1)[3, ] * 100, digits = 1))
```

#### OECD 국가 지니계수 개선도

##### 가장 낮은 나라

```{r, gini coefficient improvement, echo = FALSE}
tbl.q3 <- table(quiz0412$group, quiz0412$Q3, exclude = NULL)
Q3.tbl.am <- addmargins(tbl.q3, margin = 1)
colnames(Q3.tbl.am)[6] <- "결석"
rownames(Q3.tbl.am)[3] <- "계"
pander(Q3.tbl.am)
pander(chisq.test(tbl.q3[-3, ]))
```

##### 가장 낮은 나라 (%)

```{r, gini coefficient improvement in percentage, echo = FALSE}
pander(round(prop.table(Q3.tbl.am, margin = 1)[3, ] * 100, digits = 1))
```

### 내가 살고 싶은 세상

#### 내가 남보다, 혹은 남이 나보다

##### 소득의 절대값이 아니라 상대 비교가 중요하다는 Solnick and Henenway(1998)의 연구결과와 일치. 랜덤화하였지만 응답에는 차이가 없음.

```{r, social comparison, echo = FALSE}
Q4.tbl.e <- table(quiz0412$group, quiz0412$Q4.2, exclude = NULL)
Q4.tbl.am <- addmargins(Q4.tbl.e, margin = 1)
colnames(Q4.tbl.am)[3] <- "결석"
rownames(Q4.tbl.am)[3] <- "계"
pander(Q4.tbl.am)
```

##### % 비교.  

```{r, social comparison in percentage, echo = FALSE}
Q4.tbl <- table(quiz0412$group, quiz0412$Q4.2)
pander(round(prop.table(Q4.tbl, margin = 1)*100, digits = 1))
```

#### 합산(%)

```{r, percentage in sum, echo = FALSE}
Q4.tbl.am.2 <- addmargins(Q4.tbl, margin = 1)
pander(round(prop.table(Q4.tbl.am.2[3, ])*100, digits = 1))
```


```{r, save, echo = FALSE}
#save.image("../R/quiz0412.RData"")
```