---
title: "Quiz 170306 (Randomized Effects)"
author: "coop711"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# install.packages("pander", repos = "https://cran.rstudio.com")
# install.packages("xlsx", repos = "https://cran.rstudio.com")
library(xlsx)
library(pander)
library(knitr)
panderOptions('table.split.table', Inf)
panderOptions('table.alignment.rownames', 'left')
panderOptions('table.alignment.default', 'right')
options(width=180)
```

```{r, data, echo = FALSE, results = 'hide'}
quiz0306 <- read.xlsx("../data/quiz0306.xlsx", 1, startRow = 2, endRow = 164, colIndex = c(3:7, 9:15), colClasses=c(rep("character", 12)), stringsAsFactors=FALSE)
str(quiz0306)
names(quiz0306) <- c("dept", "id", "name", "year", "e.mail", "cell.no", "Q1", "Q2", "Q3", "Q4", "group", "group.roll")
quiz0306$dept <- factor(quiz0306$dept)
quiz0306$year <- factor(quiz0306$year)
quiz0306$group <- factor(quiz0306$group, levels = c("Red", "Black"))
quiz0306$group.roll <- factor(quiz0306$group.roll, levels = c("Red", "Black"))
quiz0306$Q1 <- factor(quiz0306$Q1, levels = c("가", "나", "다", "라", "마"), labels = c("공자", "맹자", "관자", "노자", "장자"))
quiz0306$Q2 <- factor(quiz0306$Q2, levels = c("가", "나", "다", "라", "마"), labels = c("절대 중요 않음", "거의 중요 않음", "보통", "상당히 중요", "절대 중요"))
quiz0306$Q3 <- factor(quiz0306$Q3, levels = c("가", "나", "다", "라"), labels = c("2012", "2016", "2020", "2030"))
quiz0306$Q4 <- factor(quiz0306$Q4, levels = c("가", "나", "다"), labels = c("찬성 입장", "반대 입장", "모름/무응답"))
# quiz0306$Q4.2 <- quiz0306$Q4
# levels(quiz0306$Q4.2) <- c("찬성", "반대", "모름/무응답")
str(quiz0306)
```


### 퀴즈 응답 비교

```{r, NA ingroup, echo = FALSE, results = 'markup'}
na.group <- is.na(quiz0306$group)
na.group.roll <- is.na(quiz0306$group.roll)
which(na.group)
which(na.group.roll)
quiz0306[na.group, ]
quiz0306[na.group.roll, ]
cbind(quiz0306$group[na.group], quiz0306$group.roll[na.group])
# levels(quiz0306$group.roll[na.group])
quiz0306$group[na.group] <- quiz0306$group.roll[na.group]
cbind(quiz0306$group[na.group], quiz0306$group.roll[na.group])
cbind(quiz0306$group[na.group.roll], quiz0306$group.roll[na.group.roll])
```

```{r, cross table, echo = FALSE, results = 'markup'}
# pander(summary(quiz0306))
quiz0306 <- quiz0306[!na.group.roll, ]
str(quiz0306)
reduced <- quiz0306$group == quiz0306$group.roll
which(reduced)
quiz0306 <- quiz0306[reduced, ]
cbind(quiz0306$group, quiz0306$group.roll)
tbl.q <- table("출석부" = quiz0306$group.roll, "퀴즈" = quiz0306$group)
tbl.q.a <- addmargins(tbl.q)
tbl.q.a
colnames(tbl.q.a)[3] <- c("계")
rownames(tbl.q.a)[3] <- c("계")
pander(tbl.q.a)
```

#### 춘추전국시대에 국가통계관리의 중요성 강조

##### 관자(집계표)

```{r, , Kwanzi, echo = FALSE}
# pander(table(quiz0306$group, quiz0306$Q1, exclude = NULL), caption="춘추시대 국가통계관리")
# pander(addmargins(table(quiz0306$group, quiz0306$Q1, exclude = NULL), margin=1), caption="춘추시대 국가통계관리")
Q1.tbl.am <- addmargins(table(quiz0306$group, quiz0306$Q1, exclude = NULL), margin = 1)
colnames(Q1.tbl.am)[6] <- "결석"
rownames(Q1.tbl.am)[4] <- "계"
pander(Q1.tbl.am[-3, ])
# pander(addmargins(table(quiz0306$group, quiz0306$Q1, exclude = NULL), margin=1))
```

##### 관자(%)

```{r, Kwanzi in percentage, echo = FALSE}
pander(round(prop.table(Q1.tbl.am, margin = 1)[4, ]*100, digits = 2))
# pander(round(prop.table(addmargins(table(quiz0306$group, quiz0306$Q1, exclude = NULL), margin=1), margin=1)[4,]*100, digits=1))
```

#### 국가정책을 수립하는 데 통계의 역할

##### 통계의 중요성(집계표)

```{r, state arithmetic, echo = FALSE}
# pander(table(quiz0306$group, quiz0306$Q2, exclude = NULL), caption="통계의 역할")
# pander(addmargins(table(quiz0306$group, quiz0306$Q2, exclude = NULL), margin=1), caption="통계의 역할")
Q2.tbl.am <- addmargins(table(quiz0306$group, quiz0306$Q2, exclude = NULL), margin = 1)
colnames(Q2.tbl.am)[6] <- "결석"
rownames(Q2.tbl.am)[4] <- "계"
pander(Q2.tbl.am[-3, ])
# pander(addmargins(table(quiz0306$group, quiz0306$Q2, exclude = NULL), margin=1))
```

##### 통계의 중요성(%)

```{r, state arithmetic in percentage, echo = FALSE}
pander(round(prop.table(Q2.tbl.am, margin = 1)[4, ]*100, digits = 2))
# pander(round(prop.table(addmargins(table(quiz0306$group, quiz0306$Q2, exclude = NULL), margin=1), margin=1)[4,]*100, digits=1), caption="통계의 역할")
```

#### 우리나라 생산가능인구 감소 시기

##### 생산가능인구 감소 시기(집계표)

```{r, labour force, echo = FALSE}
Q3.tbl.am <- addmargins(table(quiz0306$group, quiz0306$Q3, exclude = NULL), margin = 1)
colnames(Q3.tbl.am)[5] <- "결석"
rownames(Q3.tbl.am)[4] <- "계"
pander(Q3.tbl.am[-3, ])
# pander(table(quiz0306$group, quiz0306$Q3, exclude = NULL), caption="생산가능인구 감소")
# pander(addmargins(table(quiz0306$group, quiz0306$Q3, exclude = NULL), margin=1), caption="생산가능인구 감소")
# pander(addmargins(table(quiz0306$group, quiz0306$Q3, exclude = NULL), margin=1))
```

##### 생산가능인구 감소 시기(%)

```{r, labour force in percentage, echo = FALSE}
pander(round(prop.table(Q3.tbl.am, margin = 1)[4, ]*100, digits = 2))
# pander(round(prop.table(addmargins(table(quiz0306$group, quiz0306$Q3, exclude = NULL), margin=1), margin=1)[4,]*100, digits=1), caption="생산가능인구 감소")
```

### 테러방지법 찬반

#### 테러방지법 찬반

##### 집계표. 찬반 어느 쪽에 부연설명을 하였는가(Red는 찬성 쪽에 부연설명, Black은 반대 쪽에 부연설명)에 따라 찬반에 영향. 

```{r, anti-terror law, echo = FALSE}
thaad.tbl.e <- table(quiz0306$group, quiz0306$Q4, exclude = NULL)
colnames(thaad.tbl.e)[4] <- "결석"
pander(thaad.tbl.e[-3, ], caption ="테러방지법")
# pander(table(quiz0306$group, quiz0306$Q4, exclude = NULL), caption="테러방지법")
# pander(table(quiz0306$group, quiz0306$Q4.2, exclude = NULL), caption="테러방지법")
```

##### % 비교.  

```{r, anti-terror law in percentage, echo = FALSE}
thaad.tbl <- table(quiz0306$group, quiz0306$Q4)
# thaad.tbl.2 <- table(quiz0306$group, quiz0306$Q4.2)
# pander(round(prop.table(thaad.tbl, margin = 1)*100, digits = 1), caption="테러방지법(단위, %)")
pander(round(prop.table(thaad.tbl, margin = 1)*100, digits = 1))
# pander(round(prop.table(thaad.tbl.2, margin = 1)*100, digits = 1), caption = "테러방지법(단위, %)")
```

```{r, save, echo = FALSE}
#save.image("../R/quiz0306.rda")
```