---
title: "Red and Black 160907"
author: "coop711"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# install.packages("pander", repos = "https://cran.rstudio.com")
# install.packages("xlsx", repos = "https://cran.rstudio.com")
library(xlsx)
library(pander)
library(knitr)
panderOptions('table.split.table', Inf)
```

### New Student 

```{r, data, echo = FALSE, results = 'hide'}
class_roll0907 <- read.xlsx("../data/class_roll0907.xlsx", 1, startRow = 2, endRow = 102, colIndex = c(3:7, 9), colClasses = rep("character", 6), stringsAsFactors = FALSE)
str(class_roll0907)
names(class_roll0907) <- c("dept", "id", "name", "year", "e.mail", "cell.no")
str(class_roll0907)
load("./red_and_black_160905v2_data.rda")
(id_new.not.in.2 <- setdiff(class_roll0907$id, class_roll.2$id))
class_roll0907$name[class_roll0907$id == id_new.not.in.2]
new_student <- class_roll0907[class_roll0907$id == id_new.not.in.2, ]
```

```{r, who, echo = FALSE}
pander(new_student)
```

### Incremental Randomization

```{r, copy group, echo = FALSE, results = 'hide'}
class_roll0907$group <- class_roll.2$group[match(class_roll0907$id, class_roll.2$id)]
(new_student.no <- which(is.na(match(class_roll0907$id, class_roll.2$id))))
class_roll0907$group[new_student.no] <- ifelse(table(class_roll.2$group)[1] < table(class_roll.2$group)[2], "Red", "Black")
str(class_roll0907)
```

### 학번

```{r, id, echo = FALSE}
ID.15 <- factor(ifelse(substr(class_roll0907$id, 1, 4) >= 2015, "younger.15", "older.15"), levels = c("younger.15", "older.15"), labels = c("15학번 이후", "14학번 이전"))
pander(table("그룹" = class_roll0907$group, "15학번 기준" = ID.15))
ID.14 <- factor(ifelse(substr(class_roll0907$id, 1, 4) >= 2014, "younger.14", "older.14"), levels=c("younger.14", "older.14"), labels = c("14학번 이후", "13학번 이전"))
pander(table("그룹" = class_roll0907$group, "14학번 기준" = ID.14))
ID.13 <- factor(ifelse(substr(class_roll0907$id, 1, 4) >= 2013, "younger.13", "older.13"), levels=c("younger.13", "older.13"), labels = c("13학번 이후", "12학번 이전"))
pander(table("그룹" = class_roll0907$group, "13학번 기준" = ID.13))
ID.12 <- factor(ifelse(substr(class_roll0907$id, 1, 4) >= 2012, "younger.12", "older.12"), levels=c("younger.12", "older.12"), labels = c("12학번 이후", "11학번 이전"))
pander(table("그룹" = class_roll0907$group, "12학번 기준" = ID.12))
```

### 학번 뒷자리 홀짝

```{r, odd or even, echo = FALSE}
odd.even <- factor(as.numeric(class_roll0907$id) %% 2, levels = c(1, 0), labels = c("홀", "짝"))
pander(table("그룹"= class_roll0907$group, "홀짝" = odd.even))
```

### 학년 분포

```{r, School Year, echo = FALSE}
pander(table("그룹"= class_roll0907$group, "학년" = class_roll0907$year))
```

### e-mail 서비스 업체

```{r, e_mail, echo = FALSE}
e.mail.list <- strsplit(class_roll0907$e.mail, "@", fixed = TRUE)
mail.com <- mapply("[", e.mail.list, 2)
mail.com.f <- factor(ifelse(mail.com == "naver.com", mail.com, "기타 서비스업체"), levels = c("naver.com", "기타 서비스업체"))
pander(table("그룹" = class_roll0907$group, "e-mail" = mail.com.f))
```

<!--### 성씨 분포

```{r, name, echo = FALSE}
f.name <- substring(class_roll0907$name, first = 1, last = 1)
pander(table("그룹" = class_roll0907$group, "성씨" = f.name))
```
-->

#### 많이 나오는 성씨

```{r, frequent family name, echo = FALSE}
f.name <- substring(class_roll$name, first = 1, last = 1)
# f.name %in% c("김","이","박")
f.name.f <- factor(ifelse(f.name %in% c("김", "이", "박", "최"), f.name, "기타"), levels = c("김", "이", "박", "최", "기타"))
pander(table("Group" = class_roll$group, "Family Name" = f.name.f))
```


### 학과 분포

```{r, big departments, echo = FALSE, results = 'hide'}
(tbl.dept <- table(class_roll0907$dept))
pander(tbl.dept)
str(tbl.dept)
dept.big <- names(tbl.dept)[tbl.dept >= 8]
dept.major <- ifelse(class_roll0907$dept %in% dept.big, class_roll0907$dept, "기타 학과")
dept.major.f <- factor(dept.major, levels = c(dept.big, "기타 학과"))
# pander(table("그룹" = class_roll0907$group, "학과" = class_roll0907$dept))
```

```{r, departments, echo = FALSE}
pander(table("그룹" = class_roll0907$group, "학과" = dept.major.f))
```

### 출석부

```{r, class roll, echo = FALSE}
pander(class_roll0907)
```

### Red and Black 나누기

```{r, list, echo = FALSE, results = 'hide'}
(gr.id.o <- order(class_roll0907$group, class_roll0907$name))
(id.by.gr <- class_roll0907[gr.id.o, c("group", "id", "name")])
red.names <- id.by.gr[id.by.gr$group == "Red", c("id", "name")]
# pander(red.names)
black.names <- id.by.gr[id.by.gr$group == "Black", c("id", "name")]
# black.names.2 <- black.names
# class_roll.2[class_roll.2$name == "권현종", c("id", "name")]
# pander(black.names)
# class_roll[red.id, "id"]
# class_roll[black.id, "id"]
# cbind(class_roll[red.id, "id"], class_roll[black.id, "id"])
# red.black.df <- data.frame("Red" = red.names, "Black" = black.names, row.names = NULL)
# red.black.ls <- list("Red" = red.names, "Black" = black.names)
# names(red.black.df) <- c("Red", "Black")
# pander(red.black.ls)
#kable(red.black.df, align = c("c", "c", "c", "c"))
```

<P style="page-break-before:always">

```{r, red.names, echo = FALSE}
pander(red.names, caption = "Red")
```

<P style="page-break-before:always">

```{r, black.names, echo = FALSE}
pander(black.names, caption = "Black")
```

<!--
```{r, save}
save.image("./red_and_black_160907_data.rda")
```
-->