---
title: "SE and Coop Quiz 160322"
author: "coop711"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# install.packages("pander", repos = "https://cran.rstudio.com")
# install.packages("xlsx", repos = "https://cran.rstudio.com")
library(xlsx)
library(pander)
library(knitr)
panderOptions('table.split.table', Inf)
panderOptions('table.alignment.rownames', 'left')
panderOptions('table.alignment.default', 'right')
options(width=180)
```

```{r, data, echo = FALSE, results = 'hide'}
quiz0322 <- read.xlsx("../data/SE_Quiz160322.xlsx", 1, startRow = 2, endRow = 62, colIndex = c(3:7, 9:13), colClasses=c(rep("character", 10)), stringsAsFactors=FALSE)
str(quiz0322)
names(quiz0322) <- c("dept", "id", "name", "year", "e.mail", "cell.no", "Q1", "Q2", "Q3", "Q4")
quiz0322$dept <- factor(quiz0322$dept)
quiz0322$year <- factor(quiz0322$year)
quiz0322$Q1 <- factor(quiz0322$Q1, levels = c("가", "나", "다", "라", "마"), labels = c("금융", "산업", "유통", "지식", "언론"))
quiz0322$Q2 <- factor(quiz0322$Q2, levels = c("가", "나", "다", "라"), labels = c("일방적감원", "일방적임금삭감", "조합원의결감원", "조합원의결임금삭감"))
quiz0322$Q3 <- factor(quiz0322$Q3, levels = c("가", "나", "다", "라"), labels = c("1인1표", "1원1표", "평등임금", "고용연대"))
quiz0322$Q4 <- factor(quiz0322$Q4, levels = c("가", "나", "다", "라"), labels = c("민주적의사결정", "고용연대", "평등임금", "형평성"))
str(quiz0322)
```

```{r, randomization, echo = FALSE, results = 'hide'}
pander(summary(quiz0322))
```

### 퀴즈 응답 점검

#### 몬드라곤의 사업분야

##### 몬드라곤의 사업분야가 아닌 것

```{r, business area of Mondragon, echo = FALSE}
Q1.tbl <- table(quiz0322$Q1, exclude = NULL)
pander(Q1.tbl)
```

##### 몬드라곤의 사업분야가 아닌 것(%)

```{r, business area  of Mondragon in percentage, echo = FALSE}
pander(round(prop.table(Q1.tbl)*100, digits=1))
```

#### 파고르 그룹의 위기 대처

##### 구조조정

```{r, Fagor case, echo = FALSE}
Q2.tbl <- table(quiz0322$Q2, exclude = NULL)
pander(Q2.tbl)
```

##### 구조조정(%)

```{r, Fagor case in percentage, echo = FALSE}
pander(round(prop.table(Q2.tbl)*100, digits=1))
```

#### 협동조합과 주식회사의 큰 차이점

##### 경제민주화(집계표)

```{r, economic democracy, echo = FALSE}
Q3.tbl <- table(quiz0322$Q3, exclude = NULL)
pander(Q3.tbl)
```

##### 경제민주화(%)

```{r, economic democracy in percentage, echo = FALSE}
pander(round(prop.table(Q3.tbl)*100, digits=1))
```

### 몬드라곤의 임금 원칙

##### 동일노동 동일임금(집계표)

```{r, equal payment, echo = FALSE}
Q4.tbl <- table(quiz0322$Q4, exclude = NULL)
pander(Q4.tbl)
```

##### 동일노동 동일임금(%)

```{r, equal payment in percentage, echo = FALSE}
pander(round(prop.table(Q4.tbl)*100, digits=1))
```

```{r, save, echo = FALSE}
#save.image("../R/quiz0322.rda")
```